### PR TITLE
Skip generating trusted files if ```allow_all_but_log``` is specified in user manifest

### PR DESCRIPTION
**Pull request by aneessahib**
This is just to enable tests. The image thus generated by GSC should not be used in production

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[finalize_manifest.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-Msdp_M72zTerMF8TuFl:-Msdp_M8Eid8HKNTUV4e:b-b6k8ng) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L110)):*
> ```Python
>     already_added_files = extract_files_from_user_manifest(rendered_manifest_dict)
> 
>     if 'allow_all_but_log' not in rendered_manifest_dict['sgx'].get('file_check_policy',[]):
> ```

Please add a space before `[]):`, for better readability
___
*[finalize_manifest.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-Msdpgmn4oHu9JDoFfFi:-Msdpgmn4oHu9JDoFfFj:b2hwhc8) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L110)):*
> ```Python
>     already_added_files = extract_files_from_user_manifest(rendered_manifest_dict)
> 
>     if 'allow_all_but_log' not in rendered_manifest_dict['sgx'].get('file_check_policy',[]):
> ```

Why do you have `[]` (empty list) as the default value? This `file_check_policy` manifest option is a string, so you should have a string default value. So please replace: `[]` -> `''`.
___
*[finalize_manifest.py, line 114 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-MsdpxvcBsyhD6iv8or9:-MsdpxvcBsyhD6iv8orA:b-wt9qx4) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L114)):*
> ```Python
>         rendered_manifest_dict['sgx'].setdefault('trusted_files', []).extend(trusted_files)
>     else:
>         print("[from inside Docker container]skipping trusted files in manifest. This image must not be used in production")
> ```

We use `print(f'blablabla')` style everywhere in this file, let's be consistent. So please replace double-quotes with single-quotes (and add the `f` prefix).
___
*[finalize_manifest.py, line 114 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-Msdq66w-kFU_CUR7OBE:-Msdq66w-kFU_CUR7OBF:b-z6kv0u) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L114)):*
> ```Python
>         rendered_manifest_dict['sgx'].setdefault('trusted_files', []).extend(trusted_files)
>     else:
>         print("[from inside Docker container]skipping trusted files in manifest. This image must not be used in production")
> ```

Please replace with:
```
print(f'[from inside Docker container] Skipping trusted files generation. This image must not be used in production.')
```

What I propose in particular:
- Add a space before `Skipping`, and using a capital letter
- Adding the word `generation` so it makes more sense what exactly we're skipping
- Adding a dot at the end

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[finalize_manifest.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-Msdp_M72zTerMF8TuFl:-Mse8hAsBg8dJ2UZJiCi:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space before `[]):`, for better readability
</blockquote></details>

Done.
___
*[finalize_manifest.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-Msdpgmn4oHu9JDoFfFi:-Mse8hop393NkXyv1Air:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `[]` (empty list) as the default value? This `file_check_policy` manifest option is a string, so you should have a string default value. So please replace: `[]` -> `''`.
</blockquote></details>

Done.
___
*[finalize_manifest.py, line 114 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-MsdpxvcBsyhD6iv8or9:-Mse8i981lLwMvZZTin3:b-odaju) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We use `print(f'blablabla')` style everywhere in this file, let's be consistent. So please replace double-quotes with single-quotes (and add the `f` prefix).
</blockquote></details>

Have also added ```\t``` since we seem to give a tab space for all prints
___
*[finalize_manifest.py, line 114 at r1](https://reviewable.io/reviews/gramineproject/gsc/41#-Msdq66w-kFU_CUR7OBE:-Mse8wX67d8k4x6dg1Xn:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c701bfeb5b165b88b026549ee5be556795164d42/finalize_manifest.py#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace with:
```
print(f'[from inside Docker container] Skipping trusted files generation. This image must not be used in production.')
```

What I propose in particular:
- Add a space before `Skipping`, and using a capital letter
- Adding the word `generation` so it makes more sense what exactly we're skipping
- Adding a dot at the end
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib)

___
*[finalize_manifest.py, line 110 at r2](https://reviewable.io/reviews/gramineproject/gsc/41#-MseJHfI73pxvuhgqLCa:-MseJHfI73pxvuhgqLCb:bvdvmm5) ([raw file](https://github.com/gramineproject/gsc/blob/d78266bea378c094f4e6b027011c49addfcddec3/finalize_manifest.py#L110)):*
> ```Python
>     already_added_files = extract_files_from_user_manifest(rendered_manifest_dict)
> 
>     if 'allow_all_but_log' not in rendered_manifest_dict['sgx'].get('file_check_policy', ''):
> ```

Isn't the purpose of `allow_all_but_log` to debug which files are missing from trusted files list? Now Gramine will warn about _all_ files which are used, making this option much less useful (basically turning it into "allow all files").

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[finalize_manifest.py, line 110 at r2](https://reviewable.io/reviews/gramineproject/gsc/41#-MseJHfI73pxvuhgqLCa:-MseYOUFCCGnB2SeI0v3:bz2mz2w) ([raw file](https://github.com/gramineproject/gsc/blob/d78266bea378c094f4e6b027011c49addfcddec3/finalize_manifest.py#L110)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Primary goal of this change here is to workaround the problem of large manifest (beyond the PAL limit) being generated by GSC with some of the test workload base images that we have seen.
</blockquote></details>

Yep, as Anees explained, this trick is to skip generating large manifests.

In GSC, there shouldn't be the problem of missing files (because the list of trusted files is automatically generated). So you can think of `sgx.file_check_policy = "allow_all_but_log"` as re-purposing the feature of Gramine to solve a slightly different problem (of huge manifests). As mentioned, this is for debugging/testing purposes only.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib and @dimakuv)

___
*[finalize_manifest.py, line 110 at r2](https://reviewable.io/reviews/gramineproject/gsc/41#-MseJHfI73pxvuhgqLCa:-Msex2GO014T-KJdXak1:b-ga4wyg) ([raw file](https://github.com/gramineproject/gsc/blob/d78266bea378c094f4e6b027011c49addfcddec3/finalize_manifest.py#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, as Anees explained, this trick is to skip generating large manifests.

In GSC, there shouldn't be the problem of missing files (because the list of trusted files is automatically generated). So you can think of `sgx.file_check_policy = "allow_all_but_log"` as re-purposing the feature of Gramine to solve a slightly different problem (of huge manifests). As mentioned, this is for debugging/testing purposes only.
</blockquote></details>

Yeah, it's that "re-purposing" part which I don't like :) I.e. that a specific manifest option in the manifest in vanilla Gramine has different effect than in GSC. Maybe this should be a GSC cmdline switch instead?

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[finalize_manifest.py, line 110 at r2](https://reviewable.io/reviews/gramineproject/gsc/41#-MseJHfI73pxvuhgqLCa:-Msexs8T3pUAhelMUR71:bptlu2x) ([raw file](https://github.com/gramineproject/gsc/blob/d78266bea378c094f4e6b027011c49addfcddec3/finalize_manifest.py#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, it's that "re-purposing" part which I don't like :) I.e. that a specific manifest option in the manifest in vanilla Gramine has different effect than in GSC. Maybe this should be a GSC cmdline switch instead?
</blockquote></details>

Why do you say a different effect? It only disables the automatic generation of the trusted files list; the user-defined trusted files are still added to the final `.manifest.sgx`.

I wouldn't say that this is something completely orthogonal. Or let me put it this way: what would you expect to happen/see then, when a user GSC manifest contains `sgx.file_check_policy = "allow_all_but_log"`? The behavior proposed in this PR is not surprising to me as a user.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[finalize_manifest.py, line 110 at r2](https://reviewable.io/reviews/gramineproject/gsc/41#-MseJHfI73pxvuhgqLCa:-MsfC7WL1jP8cZXOdB5l:b-nc5syb) ([raw file](https://github.com/gramineproject/gsc/blob/d78266bea378c094f4e6b027011c49addfcddec3/finalize_manifest.py#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you say a different effect? It only disables the automatic generation of the trusted files list; the user-defined trusted files are still added to the final `.manifest.sgx`.

I wouldn't say that this is something completely orthogonal. Or let me put it this way: what would you expect to happen/see then, when a user GSC manifest contains `sgx.file_check_policy = "allow_all_but_log"`? The behavior proposed in this PR is not surprising to me as a user.
</blockquote></details>

Hmm, ok, looking at it this way makes more sense. Let's leave it as is then.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/41#-Msib1qPAdPx7-XrE5R7:-Msib1qPAdPx7-XrE5R8:b-19dfok) (no related file):*
I verified manually that this PR works correctly. From my perspective, the PR is ready for merge.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/41#-MtNnoht63smfD9DLAKI:-MtNnoht63smfD9DLAKJ:b17hw3r) (no related file):*
FYI: I manually verified that the final rebased version correctly builds "no autogenerated trusted-files list" GSC image when supplied with `allow_all_bug_log` manifest option (and that it preserves the old behavior of autogenerating this list when not supplied with this option). LGTM.

---

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
