### PR TITLE
Change license from LGPL to BSD 3 Clause

### LINKED ISSUE #161: [Metaissue] Changing the license of GSC
## Description of the problem

GSC doesn't have a separate license from the core Gramine project. In fact, the license is missing from this repository. We must add the license.

Historically, GSC lived in the same repository as the core Gramine project (at that time called Graphene): https://github.com/gramineproject/graphene/tree/master/Tools/gsc. So GSC inherited the LGPL v3 license: https://github.com/gramineproject/graphene/blob/master/LICENSE.txt.

However, the question was raised whether the LGPL license is suitable for the GSC project. See e.g. #154. Indeed, the internal recommendation for us was to use the **BSD 3 license**.

I collected the list of contributors who contributed a significant number of (sufficiently big) PRs. This list was collected via:
-  `gramineproject/gsc$ git log | grep "Signed-off-by\|Co-authored-by" | sort`
- doing some manual review of commits of separate authors from the list above
- checking the commit message of the very first commit in this repo: https://github.com/gramineproject/gsc/commit/d79ea25af3fb3c908dc882a03bcdca8451ebe154

The resulting list looks like this (no particular order):
- [x] Li Lei, via his Intel manager Mona Vij, see https://github.com/gramineproject/gsc/issues/161#issuecomment-1691820125
- [x] Anjo Vahldiek-Oberwagner
- [x] Dmitrii Kuvaiskii
- [x] Michał Kowalczyk
- [x] Veena Saini
- [x] Wojtek Porczyk
- [x] Anees Sahib
- [x] Abin Mathew
- [x] Anjali Rai
- [x] Jitender Kumar
- [x] Kailun Qin
- [x] Vijay Dhanraj
- [x] Sonali Saha

## Actions required
1. Choose the new license for this repo (the suggestion is **BSD 3-clause**)
2. Obtain explicit consent from every of the aforementioned contributors that they are Ok to change the license from LGPL v3 to BSD 3-clause.

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This change is in response to a popular request to adopt a more permissive license for GSC. This change was agreed by all contributors to GSC, past and present.

Fixes #161. See it also for more context and the voting process.

TODOs after PR is merged:
- [ ] Add the BSD license to the GitHub repo page.

## How to test this PR? 

N/A.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/169)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/169)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`LICENSE.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/169#-Ncc4JBR661Y3IWZQbjf:-Ncc4JBS5LRF5bjK6NBr:b-gv2yo6) ([raw file](https://github.com/gramineproject/gsc/blob/fbe458e13f34030c16e09418143462bd3e559729/LICENSE.txt#L1)):*
> ```help
> Copyright 2023 Gramine Contributors
> ```

I'm not sure if the date and the authors is correct. Are there better suggestions?

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/169)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`LICENSE.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/169#-Ncc4JBR661Y3IWZQbjf:-Ncc5FHR-cM70rM9hddP:b6390f3) ([raw file](https://github.com/gramineproject/gsc/blob/fbe458e13f34030c16e09418143462bd3e559729/LICENSE.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure if the date and the authors is correct. Are there better suggestions?
</blockquote></details>

Should we align w/ this: https://github.com/gramineproject/gsc/blob/dd5238699ae24c5c2e92e916f4cd18b17fba0d11/Documentation/conf.py#L25-L27?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/169)* status: 3 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`LICENSE.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/169#-Ncc4JBR661Y3IWZQbjf:-Ncc6_lr3LxTbbrlWtio:b-l2tt7p) ([raw file](https://github.com/gramineproject/gsc/blob/fbe458e13f34030c16e09418143462bd3e559729/LICENSE.txt#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we align w/ this: https://github.com/gramineproject/gsc/blob/dd5238699ae24c5c2e92e916f4cd18b17fba0d11/Documentation/conf.py#L25-L27?
</blockquote></details>

Done, good catch.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/169)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by donporter — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/169)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Pull request merged**
