### PR TITLE
Fix Dockerfile of the OpenVINO example

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The used version of OpenVINO doesn't compile on Ubuntu 18.04, so leave only a 20.04 Dockerfile. Also fix other small issues and improve README.

## How to test this PR? 

Manually.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/73#-N6NnKgG-NBIU166GmqE:-N6NnKgG-NBIU166GmqF:b-singpr) (no related file):*
Depends on #71. I'll rebase on top of #71 when it is merged.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/73#-N6NnKgG-NBIU166GmqE:-N6OpdSd9IQwZXwFt6nA:b-jborkn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, I'll need to add this diff after #71 is merged to this PR:
```diff
 # Build apps
 RUN cd /opt/intel/openvino_2021.4.582/inference_engine/samples/cpp && \
-    ./build_samples.sh && \
-    cd / && \
-    ln -sf ~/inference_engine_cpp_samples_build/intel64/Release/benchmark_app benchmark_app
+    ./build_samples.sh

 # Download models benchmark app
 RUN cd /opt/intel/openvino_2021.4.582/deployment_tools/open_model_zoo/tools/downloader && \
@@ -49,4 +51,4 @@ ENV LD_LIBRARY_PATH=/opt/intel/openvino_2021.4.582/deployment_tools/inference_en

 RUN echo "source /opt/intel/openvino_2021.4.582/bin/setupvars.sh" > /root/.bashrc

-ENTRYPOINT ["./benchmark_app"]
+ENTRYPOINT ["/root/inference_engine_cpp_samples_build/intel64/Release/benchmark_app"]
```
</blockquote></details>

Done. Ready for review.

___

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Examples/openvino/README.md` line 13 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHMpPQAe5bR057pnvx:-NBHMpPRDYGXFjAmdoIL:bwk8csb) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L13)):*
> ```Markdown
> 1. Build Docker image:
> ```bash
> docker build --rm -t ubuntu20.04-openvino -f ubuntu20.04-openvino.dockerfile .
> ```

Isn't this the default?



_Code quote:_
```Markdown
--rm 
```
___
*[`Examples/openvino/README.md` line 43 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHN28p3P3xyae6155F:-NBHN28p3P3xyae6155G:bmsq9sp) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L43)):*
> ```Markdown
> - For a quick test:
> ```bash
> $ docker run --device /dev/sgx_enclave gsc-ubuntu20.04-openvino \
> ```

Here `--rm` wouldn't hurt
___
*[`Examples/openvino/README.md` line 43 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHNFC5DBldzXLHdOvP:-NBHNFC5DBldzXLHdOvQ:bsdkzqe) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L43)):*
> ```Markdown
> - For a quick test:
> ```bash
> $ docker run --device /dev/sgx_enclave gsc-ubuntu20.04-openvino \
> ```

This assumes in-kernel driver. I guess that's what we do now?



_Code quote:_
```Markdown
/dev/sgx_enclave
```
___
*[`Examples/openvino/README.md` line 45 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHOwWsD2LAqvSXTnt6:-NBHOwWsD2LAqvSXTnt7:bdv56j8) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L45)):*
> ```Markdown
> $ docker run --device /dev/sgx_enclave gsc-ubuntu20.04-openvino \
>     -m model/public/resnet-50-tf/FP16/resnet-50-tf.xml \
>     -d CPU -b 1 -t 20 -nstreams 72 -nthreads 72 -nireq 72
> ```

What if I don't have 72 cpus?
___
*[`Examples/openvino/README.md` line 60 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHP6uP6jqCl220RJ2s:-NBHP6uP6jqCl220RJ2t:b-slv9mx) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L60)):*
> ```Markdown
> 
> - For a quick test:
> ```bash
> ```

ditto (`--rm`)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`Examples/openvino/README.md` line 13 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHMpPQAe5bR057pnvx:-NBLi6K_1rhYDJi7Df5i:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't this the default?
</blockquote></details>

Done.
___
*[`Examples/openvino/README.md` line 43 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHNFC5DBldzXLHdOvP:-NBLhUAQ5kAuEqH4QJ0U:bwdpucl) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This assumes in-kernel driver. I guess that's what we do now?
</blockquote></details>

Well, this is only an example. I don't want to write `<choose your SGX driver under /dev/ here>` in every example of a command.

And yes, I think we should assume the in-kernel driver as the default.
___
*[`Examples/openvino/README.md` line 43 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHN28p3P3xyae6155F:-NBLiIYc4WPwlAwejUVF:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Here `--rm` wouldn't hurt
</blockquote></details>

Done.
___
*[`Examples/openvino/README.md` line 45 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHOwWsD2LAqvSXTnt6:-NBLhkLV7Hp-H0GJau6c:b-m2a7g7) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What if I don't have 72 cpus?
</blockquote></details>

You decrease the number? I mean, nothing bad will happen, it's just that the performance will be sub-optimal (72 threads will be multiplexed over your number of CPUs).

Do you want me to decrease this number to e.g. `4`?
___
*[`Examples/openvino/README.md` line 60 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHP6uP6jqCl220RJ2s:-NBLiOZ6B3z056G-vNYg:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`--rm`)
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Examples/openvino/README.md` line 45 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHOwWsD2LAqvSXTnt6:-NBMhC_j84KGVxt0MSs8:bhloxic) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You decrease the number? I mean, nothing bad will happen, it's just that the performance will be sub-optimal (72 threads will be multiplexed over your number of CPUs).

Do you want me to decrease this number to e.g. `4`?
</blockquote></details>

I'm not sure, `72` is just some random number, which I guess is rather high. Maybe put even `2` or `1`? If you assume that people will tweak it anyway, then better put something as small as possible

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/73#-NBN4n2P3nLbJdBk56v0:-NBN4n2Q4b-Oqf2xXrCq:b-v87kk5) (no related file):*
Let me block myself. I want to verify that it still works correctly on a big-ish SGX platform.

___
___
*[`Examples/openvino/README.md` line 45 at r2](https://reviewable.io/reviews/gramineproject/gsc/73#-NBHOwWsD2LAqvSXTnt6:-NBN4fZr5ZKk_ekuDtgC:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1f7fc9a24684f6d4d0f4ddf188f488e24a42392e/Examples/openvino/README.md#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not sure, `72` is just some random number, which I guess is rather high. Maybe put even `2` or `1`? If you assume that people will tweak it anyway, then better put something as small as possible
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/73#-NBN4n2P3nLbJdBk56v0:-NBNeKEXCE6NQkm9yQf-:bnlgprb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me block myself. I want to verify that it still works correctly on a big-ish SGX platform.
</blockquote></details>

Done. Tested on a large SGX platform, works fine.

(Interestingly, I first tried on an SGX platform with CentOS 8 as the host, but just building the base OpenVINO Docker image broke. I don't know why this happens.)

___

**Review by dimakuv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
