### PR TITLE
[Docs] Change email group address to our alias

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes

See https://github.com/gramineproject/gramine/pull/241.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/32#-MpA6a_J9nVYnALWsrWc:-MpA6a_K8MrNCm4UdihV:bnqhpn6) ([raw file](https://github.com/gramineproject/gsc/blob/844091cbf51814dca840bf9f41b527769e663edb/.github/ISSUE_TEMPLATE.md#L7)):*
> ```Markdown
> 
> IMPORTANT: please do not post general questions here;
> if you have questions, please use our mailing list: devel@gramineproject.io
> ```

`users@`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/32#-MpA6a_J9nVYnALWsrWc:-MpCmAVs1oYW9a74OZsn:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/844091cbf51814dca840bf9f41b527769e663edb/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`users@`?
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/32)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
