### PR TITLE
Add GitHub PR and Issue templates

### PR DESCRIPTION
**Pull request by mkow**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-Mk8jY521IXQjjPJY6h4:b3pljzc) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
> ```Markdown
>

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-Mk8nWFW4fAZYl1runyC:b6a1al1) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we remove the ### or change it to some other char? I often leave this because I think it's the template header...
</blockquote></details>

It's in a comment, so does it really matter?
I chose `#` because it's pretty visible (still not visible enough for everyone though, but that's the best I could think of :) ).

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-Mk956087WpW0tbYSgeL:b-4rkcyp) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's in a comment, so does it really matter?
I chose `#` because it's pretty visible (still not visible enough for everyone though, but that's the best I could think of :) ).
</blockquote></details>

Ofc it doesn't get rendered, it's just when I see this template when creating a new issue, I often delete the comments (because they take space on the screen and it's annoying to write with them) and I tend to make a mistake of removing everything from the start of the comment (`<!--`) to this `###` because I think it's the next header. Just something that annoyed me ever since, but if nobody else has this problem, then go ahead and merge this.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-Mk9W8cCCx4I6LjWOtlC:b-3veza2) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ofc it doesn't get rendered, it's just when I see this template when creating a new issue, I often delete the comments (because they take space on the screen and it's annoying to write with them) and I tend to make a mistake of removing everything from the start of the comment (`<!--`) to this `###` because I think it's the next header. Just something that annoyed me ever since, but if nobody else has this problem, then go ahead and merge this.
</blockquote></details>

Ah, I see. Never happened to me, but I can change it if you propose another version, which is equally visible.

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-Mk9m8RB4YQfmRweG6P3:b-cupolz) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I see. Never happened to me, but I can change it if you propose another version, which is equally visible.
</blockquote></details>

`@@@` seems to be even more visible

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-MkCK-Fy2tYMo2UwmTtX:bjswnqs) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`@@@` seems to be even more visible
</blockquote></details>

Looks good. If @dimakuv also likes it then I'll change it here and in the other repos.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-MkCXjoCEqMiqRfTWw5b:b-7zvd3t) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks good. If @dimakuv also likes it then I'll change it here and in the other repos.
</blockquote></details>

I'm fine with `@@@`. Let's do this change, sure.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: 1 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[.github/ISSUE_TEMPLATE.md, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/17#-Mk8jY517PhDSgBDoxXF:-MkC_vUEE58ouIYC09en:bqvybq) ([raw file](https://github.com/gramineproject/gsc/blob/9d6a73cdc4a0bd4fee6e89a1e64212b575b2df66/.github/ISSUE_TEMPLATE.md#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with `@@@`. Let's do this change, sure.
</blockquote></details>

Done. As this change is trivial, I also rebased it at the same time.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[.github/ISSUE_TEMPLATE.md, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/17#-MkCbgV6-zUux4_G3R3M:-MkCbgV763CVj0H60czK:b3bx26t) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/.github/ISSUE_TEMPLATE.md#L7)):*
> ```Markdown
> 
> IMPORTANT: please do not post general questions here;
> if you have questions, please use mailing list: support@graphene-project.io
> ```

BTW, we'll need to fix "graphene-project" when we work on/review the "Rename to Gramine" PR
___
*[.github/PULL_REQUEST_TEMPLATE.md, line 4 at r2](https://reviewable.io/reviews/gramineproject/gsc/17#-MkCbotFA2TUVe9Rq_Dm:-MkCbotFA2TUVe9Rq_Dn:b-50m28a) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/.github/PULL_REQUEST_TEMPLATE.md#L4)):*
> ```Markdown
>     Please fill in the following form before submitting this PR
>     and ensure that your code follows our coding style guideline:
>     https://graphene.readthedocs.io/en/latest/devel/coding-style.html -->
> ```

BTW, ditto

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
