### PR TITLE
Update to v1.6

### PR DESCRIPTION
**Pull request by jkr0103**
## Description of the changes 

Same as these commits for previous v1.5:

https://github.com/gramineproject/gsc/commit/c0be56daaa5a3a8a94f1b9c11a241100fec18b4b
https://github.com/gramineproject/gsc/commit/c2990e0c2bb3d5c5eaec664c7c8a6fb6d3c81e2e

## How to test this PR? 

Test manually.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhUibA9IJ4wpYBDRXj):*
(to match the other commits)



_Suggestion:_
```
Update config template to `master` branch
```
___
*[`Documentation/index.rst` line 345 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhVX9q-eEGt9HTQjZD:-NlhVX9q-eEGt9HTQjZE:b4kmz66) ([raw file](https://github.com/gramineproject/gsc/blob/2954d3581716e282cc06283675336ad04e008325/Documentation/index.rst#L345)):*
> ```reStructuredText
> .. describe:: Gramine.Branch
> 
>    Use this release/branch of the repository. Default value: ``v1.6``.
> ```

Hmm, isn't the default value `master` after the second commit?

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103 and @mkow)

___
*[`Documentation/index.rst` line 345 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhVX9q-eEGt9HTQjZD:-NlhWOzYBJbwxIRiC70D:b-6qwpq2) ([raw file](https://github.com/gramineproject/gsc/blob/2954d3581716e282cc06283675336ad04e008325/Documentation/index.rst#L345)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, isn't the default value `master` after the second commit?
</blockquote></details>

But do we care about this? We didn't update this in previous cases.

I think the reasoning is like this:
1. People only see the `stable` version of the documentation by default
2. Almost noone looks into the `latest` version (aka master) of documentation
3. So there's no need to modify the docs in the second commit, since noone will see that change anyway.

However, no strong opinion here. If you insist, we can change to `master` in the second commit.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @jkr0103)

___
*[`Documentation/index.rst` line 345 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhVX9q-eEGt9HTQjZD:-NlhX51h9BMVVMir4fyJ:bbta3p7) ([raw file](https://github.com/gramineproject/gsc/blob/2954d3581716e282cc06283675336ad04e008325/Documentation/index.rst#L345)):*
> We didn't update this in previous cases.

But wasn't that an overlook, not a conscious decision?

Regarding the reasoning: all the points you stated are about low severity of this, but without providing any pros of not updating it. Isn't it just strictly better to have the right value stated here?

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

___
*[`Documentation/index.rst` line 345 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhVX9q-eEGt9HTQjZD:-NlhXtzU-APOyhRWj0ld:b-fbpy3p) ([raw file](https://github.com/gramineproject/gsc/blob/2954d3581716e282cc06283675336ad04e008325/Documentation/index.rst#L345)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We didn't update this in previous cases.

But wasn't that an overlook, not a conscious decision?

Regarding the reasoning: all the points you stated are about low severity of this, but without providing any pros of not updating it. Isn't it just strictly better to have the right value stated here?
</blockquote></details>

Yeah, ok, strictly better it is :)

@jkr0103 Could you please update the PR (the second commit) with such a change? You can also change the commit body message per other Michal's comment and force-push the updated version.

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhUibA9IJ4wpYBDRXj):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(to match the other commits)
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 345 at r1](https://reviewable.io/reviews/gramineproject/gsc/186#-NlhVX9q-eEGt9HTQjZD:-Nlh_HI41iyZfpUhj4jh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2954d3581716e282cc06283675336ad04e008325/Documentation/index.rst#L345)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, ok, strictly better it is :)

@jkr0103 Could you please update the PR (the second commit) with such a change? You can also change the commit body message per other Michal's comment and force-push the updated version.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/186)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
