### PR TITLE
Add README and gitignore

### PR DESCRIPTION
**Pull request by dimakuv**
Contents are based on the core Gramine repo.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)* status: all files reviewed, 4 unresolved discussions (waiting on @dimakuv)

___
*[.gitignore, line 25 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEdTRN2Jtl-UlyhKSM:-MjEdTRN2Jtl-UlyhKSN:b354p86) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/.gitignore#L25)):*
> ```ignore
> *.token
> 
> # gnu global
> ```

what's this?
___
*[.gitignore, line 31 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEdVffCgmXpG4FoUml:-MjEdVffCgmXpG4FoUmm:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/.gitignore#L31)):*
> ```ignore
> GRTAGS
> 
> # tags/etags
> ```

ditto
___
*[.gitignore, line 35 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEd_49CZGKMApkLt6F:-MjEd_49CZGKMApkLt6G:bmggbs7) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/.gitignore#L35)):*
> ```ignore
> TAGS
> 
> # cscope
> ```

Why this? This repo won't really have too much C code, it's mostly Makefiles, manifests and readmes.
___
*[README.rst, line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEeHWs9zL3_O6AydGw:-MjEeHWs9zL3_O6AydGx:b-fxsooh) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/README.rst#L24)):*
> ```
> container of an image
> ```

I know this is copied from the old docs, but it sounds really weird. Could you reword it? It definitely shouldn't be "of" here.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @mkow)

___
*[.gitignore, line 25 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEdTRN2Jtl-UlyhKSM:-MjF1aMY7aOG4eQHf2QA:b-cqj48y) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/.gitignore#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

Done. This was taken from the core Gramine's `.gitignore` file. These are for the `gtags` utility. But no sense in them here, of course.
___
*[.gitignore, line 31 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEdVffCgmXpG4FoUml:-MjF1olSEc1MO8j2kvnb:bhvs7gd) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/.gitignore#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done (same as above but for `etags` for Emacs).
___
*[.gitignore, line 35 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEd_49CZGKMApkLt6F:-MjF1wjD1WxRHiFO_Vhd:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/.gitignore#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why this? This repo won't really have too much C code, it's mostly Makefiles, manifests and readmes.
</blockquote></details>

Done
___
*[README.rst, line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/6#-MjEeHWs9zL3_O6AydGw:-MjF2sB4-7YtMFqt0SPO:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/615d02a40730066d44bfa65db69a7272059729ef/README.rst#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> container of an image
> ```

I know this is copied from the old docs, but it sounds really weird. Could you reword it? It definitely shouldn't be "of" here.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dimakuv)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
