### PR TITLE
[docker] Add NASM as an essential component

### PR DESCRIPTION
**Pull request by oshogbo**
## Description of the changes 

In PR https://github.com/gramineproject/gramine/pull/541 we added NASM as an essential component.
Reflect that in the dockerfiles.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`templates/centos/Dockerfile.compile.template` line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/55#-N0Vi66s2JkWQIMVWCFk:-N0Vi66s2JkWQIMVWCFl:bdl0z87) ([raw file](https://github.com/gramineproject/gsc/blob/c41b42fcc8f664e250c67c902e0950d66790712c/templates/centos/Dockerfile.compile.template#L24)):*
> ```
>         make \
>         ncurses-devel \
>         nasm \
> ```

NP: not sorted

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`templates/centos/Dockerfile.compile.template` line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/55#-N0Vi66s2JkWQIMVWCFk:-N0Vipsj8Shsvb2gab2P:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c41b42fcc8f664e250c67c902e0950d66790712c/templates/centos/Dockerfile.compile.template#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: not sorted
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`Examples/openvino/ubuntu18.04-openvino.dockerfile` line 11 at r2](https://reviewable.io/reviews/gramineproject/gsc/55#-N0Zbsl8Co-KePPjGUHU:-N0Zbsl9D1kXlQUYxL8O:b-fq1672) ([raw file](https://github.com/gramineproject/gsc/blob/6055b7f3fb2d4ea9de3a6d00c739439aae279738/Examples/openvino/ubuntu18.04-openvino.dockerfile#L11)):*
> ```Dockerfile
>     git \
>     gnupg \
>     nasm \
> ```

This is not needed. This Dockerfile is for OpenVINO build, not Gramine build.
___
*[`Examples/openvino/ubuntu20.04-openvino.dockerfile` line 11 at r2](https://reviewable.io/reviews/gramineproject/gsc/55#-N0Zbwef6BQk_ygWM-Yn:-N0Zbwef6BQk_ygWM-Yo:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/6055b7f3fb2d4ea9de3a6d00c739439aae279738/Examples/openvino/ubuntu20.04-openvino.dockerfile#L11)):*
> ```Dockerfile
>     git \
>     gnupg \
>     nasm \
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/55#-N0ZfH9qCysskoM1Lfz9:-N0ZfH9r-2lnKL30Jo94:b-dnbswe) (no related file):*
FYI: I manually verified that the PR works. Just in case.

---

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Examples/openvino/ubuntu18.04-openvino.dockerfile` line 11 at r2](https://reviewable.io/reviews/gramineproject/gsc/55#-N0Zbsl8Co-KePPjGUHU:-N0aA7wG7jLUZVS6gG7n:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6055b7f3fb2d4ea9de3a6d00c739439aae279738/Examples/openvino/ubuntu18.04-openvino.dockerfile#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not needed. This Dockerfile is for OpenVINO build, not Gramine build.
</blockquote></details>

Done.
___
*[`Examples/openvino/ubuntu20.04-openvino.dockerfile` line 11 at r2](https://reviewable.io/reviews/gramineproject/gsc/55#-N0Zbwef6BQk_ygWM-Yn:-N0aAAYv4GTgNlKs_qXv:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6055b7f3fb2d4ea9de3a6d00c739439aae279738/Examples/openvino/ubuntu20.04-openvino.dockerfile#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gsc/55#-N0aETMo2WSdiYRptZJM):*
FYI: I updated the commit message so it reflects why we're doing this.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
