### PR TITLE
Update installation of `python3-pyelftools` for CentOS

### PR DESCRIPTION
**Pull request by aniket-intelx**
This package is provided by `epel.repo` and hence installed after
the installation of `epel-release`.

Signed-off-by: Aniket Borkar <aniketx.borkar@intel.com>

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aniket-intelx)

___
*[`templates/centos/Dockerfile.build.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/79#-N6mljN7AVE6wGASEmGN:-N6mljN7AVE6wGASEmGO:b-lnnsb0) ([raw file](https://github.com/gramineproject/gsc/blob/c80afd8ae7fef22b09e079d91df7d615e68d52fd/templates/centos/Dockerfile.build.template#L20)):*
> ```
>     && /usr/bin/python3 -B -m pip install click jinja2 protobuf 'toml>=0.10'
> 
> RUN dnf install -y python3-pyelftools
> ```

Please add a comment explaining why we need this weird split.

**Comment by aniket-intelx** [comment]
*[`templates/centos/Dockerfile.build.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/79#-N6mljN7AVE6wGASEmGN:-N6pjQmXB6_8VGJlUzse:bs7wumb) ([raw file](https://github.com/gramineproject/gsc/blob/c80afd8ae7fef22b09e079d91df7d615e68d52fd/templates/centos/Dockerfile.build.template#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a comment explaining why we need this weird split.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aniket-intelx and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/79#-N6qilbSAy96HVsTZBh-:-N6qilbT91ThjRgM6Qtr:b-22t5hw) (no related file):*
I manually verified that this change works (and before this change, CentOS 8 didn't work). Thanks for the PR!

___
___
*[`templates/centos/Dockerfile.build.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gsc/79#-N6qd2i7ErbxfLfuOd9R:-N6qd2i7ErbxfLfuOd9S:b-ii4qh7) ([raw file](https://github.com/gramineproject/gsc/blob/e9f2deae16376ecc2a2204bb62d7839a71818c6e/templates/centos/Dockerfile.build.template#L21)):*
> ```
> 
> # Install pyelftools after the installation of epel-release as it is provided
> # by epel.repo
> ```

No need to wrap into two lines, it all fits in one line (in code files we have a line limit of 100 chars).

Also, I suggest slight rephrasing:
```
# install pyelftools after the installation of epel-release as it is provided by the EPEL repo
```

**Comment by aniket-intelx** [comment]
*[`templates/centos/Dockerfile.build.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gsc/79#-N6qd2i7ErbxfLfuOd9R:-N6qmt6T4baHDXIE6d2h:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/e9f2deae16376ecc2a2204bb62d7839a71818c6e/templates/centos/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need to wrap into two lines, it all fits in one line (in code files we have a line limit of 100 chars).

Also, I suggest slight rephrasing:
```
# install pyelftools after the installation of epel-release as it is provided by the EPEL repo
```
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`templates/centos/Dockerfile.build.template` line 21 at r3](https://reviewable.io/reviews/gramineproject/gsc/79#-N6rG6_h91o5c3jv16Ob:-N6rG6_h91o5c3jv16Oc:b-5ndzjm) ([raw file](https://github.com/gramineproject/gsc/blob/af3727a68be8539c8817ffd9e0769efc1fad366f/templates/centos/Dockerfile.build.template#L21)):*
> ```
> 
> # Install pyelftools after the installation of epel-release as it is provided by the EPEL repo
> RUN dnf install -y python3-pyelftools
> ```

Shouldn't this be run in the previous command execution? Now we run `update + install + 2nd install` in one dockerfile `RUN` and then another install here, looks weird.
Not blocking as others seemed to be fine with it.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`templates/centos/Dockerfile.build.template` line 21 at r3](https://reviewable.io/reviews/gramineproject/gsc/79#-N6rG6_h91o5c3jv16Ob:-N6rGtSx-xGVNyHZQ2gV:b-vwiy9i) ([raw file](https://github.com/gramineproject/gsc/blob/af3727a68be8539c8817ffd9e0769efc1fad366f/templates/centos/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be run in the previous command execution? Now we run `update + install + 2nd install` in one dockerfile `RUN` and then another install here, looks weird.
Not blocking as others seemed to be fine with it.
</blockquote></details>

This was mostly for readability reasons. Otherwise it would be hard to put the comment.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/79)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Pull request merged**
