### PR TITLE
[Docs] Update logo

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The logo is taken from Gramine's repo: https://github.com/gramineproject/gramine/blob/master/Documentation/gramine_logo.svg

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/76)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/76)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/76#-N6ligai0N4-1cpDCKsu):*
Update from what to what? This description explains nothing :)



_Code quote:_
```
Update logo
```

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/76#-N6ligai0N4-1cpDCKsu):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Update from what to what? This description explains nothing :)
</blockquote></details>

I guess because original commit did the same: https://github.com/gramineproject/gramine/commit/b2055ab935bd410829b262ef241b13e487fb3382

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/76#-N6ligai0N4-1cpDCKsu):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess because original commit did the same: https://github.com/gramineproject/gramine/commit/b2055ab935bd410829b262ef241b13e487fb3382
</blockquote></details>

Well, that's unfair, Borys got away with it in the past: https://github.com/gramineproject/gramine/pull/335/commits :)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/76#-N6ligai0N4-1cpDCKsu):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, that's unfair, Borys got away with it in the past: https://github.com/gramineproject/gramine/pull/335/commits :)
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/76)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/76#-N6ligai0N4-1cpDCKsu):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Ah, he tricked us by having a proper explanation in the PR description, but not in the commit :)

**Pull request merged**
