### PR TITLE
Skip inaccessible trusted files

### LINKED ISSUE #142: graminize-sgx-sign fails with Permission Denied when using non-root image
## Description of the problem

I created a non-root docker image, similar to #30.  When I try to sign the image using `gsc sign-image`, it throws this error:
>PermissionError: [Errno 13] Permission denied: '/etc/default/cacerts'

I verified `/etc/default/cacerts` is owned by root and _not_ readable by others:
```bash
$ ls -Fal /etc/default/cacerts 
-rw------- 1 root root 384 Jan  5 21:48 /etc/default/cacerts
```

I verified the `unsigned_image` stage of the [Dockerfile.common.sign.template](https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.common.sign.template#L2) file is running as my `nonroot` user, so that explains why there is a permissions error. If I change this:
```docker
FROM {{image}} as unsigned_image
COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem
```
to this:
```
FROM {{image}} as unsigned_image
USER root
COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem
```
Then that fixes the problem.

## Steps to reproduce
I'm using GSC at commit dbc17b6a118d0fb13411d3acd1f1dfc032b77b83.

1. Create a non-root docker image.  See #30 for an example.
2. Run `gsc build`
3. Run `gsc sign-image`

## Expected results
The image is succesfully signed.

## Actual results

This error is thrown:
```
 ---> Running in d6e27a33102b
spawn gramine-sgx-sign --key /gramine/app_files/gsc-signer-key.pem --manifest /gramine/app_files/entrypoint.manifest --output /gramine/app_files/entrypoint.manifest.sgx
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 74, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 34, in main
    expanded = manifest.expand_all_trusted_files()
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 180, in expand_all_trusted_files
    append_trusted_dir_or_file(trusted_files, tf, expanded)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 72, in append_trusted_dir_or_file
    append_tf(trusted_files, path)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 43, in append_tf
    trusted_files[path] = hash_ if hash_ is not None else hash_file_contents(path)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 30, in hash_file_contents
    with open(path, 'rb') as f:
PermissionError: [Errno 13] Permission denied: '/etc/default/cacerts'
Removing intermediate container d6e27a33102b
```

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Fixes #142. See for context there.

## How to test this PR? 

Try some non-root Docker image with some files accessible only by root.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)

### CODE REVIEW

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`finalize_manifest.py` line 73 at r1](https://reviewable.io/reviews/gramineproject/gsc/143#-NUelAvD3flhxsf7BCx2:-NUelAvD3flhxsf7BCx3:b5y1c0z) ([raw file](https://github.com/gramineproject/gsc/blob/ebc52195a32035e158e4b823991d28e4a5ad045c/finalize_manifest.py#L73)):*
> ```Python
>             filename = os.path.join(dirpath, file)
>             if not os.path.isfile(filename) or not os.access(filename, os.R_OK):
>                 # only regular files are added as trusted files
> ```

nit: accessible regular files



_Code quote:_
```Python
regular files
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`finalize_manifest.py` line 73 at r1](https://reviewable.io/reviews/gramineproject/gsc/143#-NUelAvD3flhxsf7BCx2:-NUflR1Q7UsxZMTpoQtY:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebc52195a32035e158e4b823991d28e4a5ad045c/finalize_manifest.py#L73)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

nit: accessible regular files
</blockquote></details>

Done

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`finalize_manifest.py` line 73 at r2](https://reviewable.io/reviews/gramineproject/gsc/143#-NWKOpBPC2paxmCCd7Lk:-NWKOpBPC2paxmCCd7Ll:b1qwnhy) ([raw file](https://github.com/gramineproject/gsc/blob/e04dba1a42ed044c381d19ee1415f9598e5f9321/finalize_manifest.py#L73)):*
> ```Python
>             filename = os.path.join(dirpath, file)
>             if not os.path.isfile(filename) or not os.access(filename, os.R_OK):
>                 # only accessible regular files are added as trusted files
> ```

Not sure if silently skipping files is a good idea, in a case of weird filename (below) we're printing a warning. Bad thing about printing warnings is that non-root images will generate quite a lot of them... What do you think?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/143#-NWLx47uC9zscvcLqRKc:-NWLx47uC9zscvcLqRKd:b-iyudd4) (no related file):*
Here is the Dockerfile I used for experiments in this PR:
```bash
gsc$ cat test/ubuntu18.04-bash.dockerfile

FROM ubuntu:18.04
RUN apt-get update

RUN echo "Hello world" > /helloworld.txt \
    && chown root:root /helloworld.txt \
    && chmod 700 /helloworld.txt

RUN useradd -s /bin/bash  -m -d /home/testuser testuser
USER testuser
CMD ["bash"]
```

Then I did:
```
docker build --tag ubuntu18.04-bash --file test/ubuntu18.04-bash.dockerfile .
./gsc build --insecure-args ubuntu18.04-bash test/ubuntu18.04-bash.manifest
```

And looked at the print-outs of `gsc build` step. See my inline comment below for results.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/143#-NWLzZ4L1Rl8G0bqYOxC:-NWLzZ4L1Rl8G0bqYOxD:b-o014g5) (no related file):*
I had to rebase to the latest master, because otherwise the Intel SGX PGP key was wrong, and GSC failed.

___
___
*[`finalize_manifest.py` line 73 at r2](https://reviewable.io/reviews/gramineproject/gsc/143#-NWKOpBPC2paxmCCd7Lk:-NWLw7x965S5O2NiP8PV:bpmp0hg) ([raw file](https://github.com/gramineproject/gsc/blob/e04dba1a42ed044c381d19ee1415f9598e5f9321/finalize_manifest.py#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure if silently skipping files is a good idea, in a case of weird filename (below) we're printing a warning. Bad thing about printing warnings is that non-root images will generate quite a lot of them... What do you think?
</blockquote></details>

Done.

I don't think it's too bad, check the result of my experiments (described in a top-level comment in this PR):

- With the new check NOT moved after the `exclude_re` check:
```
Step 29/30 : RUN chmod u+x /gramine/app_files/apploader.sh     && /usr/bin/python3 -B /gramine/app_files/finalize_manifest.py     && rm -f /gramine/app_files/finalize_manifest.py

 ---> Running in 592d061e9484
        [from inside Docker container] File b'/helloworld.txt' is inaccessible!
        [from inside Docker container] File b'/etc/.pwd.lock' is inaccessible!
        [from inside Docker container] File b'/etc/gshadow' is inaccessible!
        [from inside Docker container] File b'/etc/shadow' is inaccessible!
        [from inside Docker container] File b'/etc/shadow-' is inaccessible!
        [from inside Docker container] File b'/etc/gshadow-' is inaccessible!
        [from inside Docker container] File b'/etc/security/opasswd' is inaccessible!
        [from inside Docker container] File b'/proc/kmsg' is inaccessible!
        [from inside Docker container] File b'/proc/slabinfo' is inaccessible!
        [from inside Docker container] File b'/proc/kpagecount' is inaccessible!
        [from inside Docker container] File b'/proc/kpageflags' is inaccessible!
        [from inside Docker container] File b'/proc/kpagecgroup' is inaccessible!
        [from inside Docker container] File b'/proc/vmallocinfo' is inaccessible!
        [from inside Docker container] File b'/proc/pagetypeinfo' is inaccessible!
        [from inside Docker container] File b'/proc/sysrq-trigger' is inaccessible!
        [from inside Docker container] Found 8824 files in `/`.
        [from inside Docker container] Successfully finalized `/gramine/app_files/entrypoint.manifest`.
```

- With the new check MOVED after the `exclude_re` check:
```
 ---> Running in 8f19ca883ae9
        [from inside Docker container] File /helloworld.txt is inaccessible!
        [from inside Docker container] Found 8824 files in `/`.
        [from inside Docker container] Successfully finalized `/gramine/app_files/entrypoint.manifest`.
```

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`finalize_manifest.py` line 73 at r2](https://reviewable.io/reviews/gramineproject/gsc/143#-NWKOpBPC2paxmCCd7Lk:-NWN3TRyAqYmATMubx3-:b-vs1prh) ([raw file](https://github.com/gramineproject/gsc/blob/e04dba1a42ed044c381d19ee1415f9598e5f9321/finalize_manifest.py#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

I don't think it's too bad, check the result of my experiments (described in a top-level comment in this PR):

- With the new check NOT moved after the `exclude_re` check:
```
Step 29/30 : RUN chmod u+x /gramine/app_files/apploader.sh     && /usr/bin/python3 -B /gramine/app_files/finalize_manifest.py     && rm -f /gramine/app_files/finalize_manifest.py

 ---> Running in 592d061e9484
        [from inside Docker container] File b'/helloworld.txt' is inaccessible!
        [from inside Docker container] File b'/etc/.pwd.lock' is inaccessible!
        [from inside Docker container] File b'/etc/gshadow' is inaccessible!
        [from inside Docker container] File b'/etc/shadow' is inaccessible!
        [from inside Docker container] File b'/etc/shadow-' is inaccessible!
        [from inside Docker container] File b'/etc/gshadow-' is inaccessible!
        [from inside Docker container] File b'/etc/security/opasswd' is inaccessible!
        [from inside Docker container] File b'/proc/kmsg' is inaccessible!
        [from inside Docker container] File b'/proc/slabinfo' is inaccessible!
        [from inside Docker container] File b'/proc/kpagecount' is inaccessible!
        [from inside Docker container] File b'/proc/kpageflags' is inaccessible!
        [from inside Docker container] File b'/proc/kpagecgroup' is inaccessible!
        [from inside Docker container] File b'/proc/vmallocinfo' is inaccessible!
        [from inside Docker container] File b'/proc/pagetypeinfo' is inaccessible!
        [from inside Docker container] File b'/proc/sysrq-trigger' is inaccessible!
        [from inside Docker container] Found 8824 files in `/`.
        [from inside Docker container] Successfully finalized `/gramine/app_files/entrypoint.manifest`.
```

- With the new check MOVED after the `exclude_re` check:
```
 ---> Running in 8f19ca883ae9
        [from inside Docker container] File /helloworld.txt is inaccessible!
        [from inside Docker container] Found 8824 files in `/`.
        [from inside Docker container] Successfully finalized `/gramine/app_files/entrypoint.manifest`.
``` 
</blockquote></details>

Looks good!

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/143)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Pull request merged**
