### PR TITLE
Update GSC to point at v1.3.1 release

### PR DESCRIPTION
**Pull request by aneessahib**
Update GSC to point at V1.3.1 release

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/94#-NCyk5w83nG7LyiR5Iy3:-NCyk5wA8N-AAk5OgW8p:b-e0vle6) (no related file):*
I need to test this. Blocking myself.

___

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/94#-NCykVxyE9dsURctG4jb):*
(I think? not sure though)



_Suggestion:_
```
to v1.3
```

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/94#-NCyk5w83nG7LyiR5Iy3:-NCynRzt2a7imhuTwFY7:b-c5wu20) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I need to test this. Blocking myself.
</blockquote></details>

Done. Seems to work.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/94#-NCykVxyE9dsURctG4jb):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(I think? not sure though)
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/94#-ND3UC8Z3zVaHa6W2Rcw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It will be `v1.3.1` (after we release it, in 1-2 days)
</blockquote></details>

Done
___
*[`config.yaml.template` line 15 at r2](https://reviewable.io/reviews/gramineproject/gsc/94#-ND3UGUn1c1KWSn5iqmO:-NDD72z_-rmtO8jlD5c_:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/51907a4f350c4cd2eeeb09f2dcd858b34dc00d90/config.yaml.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It will be `v1.3.1` (after we release it, in 1-2 days)
</blockquote></details>

Done

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/94#-NDD9Y8VC54MkvW98poo:-NDD9Y8W7zHtfhSPOFXA:babnd4h) (no related file):*
This should be merged with https://github.com/gramineproject/gsc/pull/95 into a single commit, otherwise this commit will leave the repo in a broken state (partially updated to v1.3.1, but partially not).

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/94)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/94#-NDD9Y8VC54MkvW98poo:-NDDC-K52cW8ektZYsa3:b-lqbygm) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be merged with https://github.com/gramineproject/gsc/pull/95 into a single commit, otherwise this commit will leave the repo in a broken state (partially updated to v1.3.1, but partially not).
</blockquote></details>

Done. Updated #95, closing this one.

___

**Comment by dimakuv** [comment]
Superseded by https://github.com/gramineproject/gsc/pull/95

**Pull request closed without merging**
