### PR TITLE
Add support for CentOS Stream 9

### PR DESCRIPTION
**Pull request by adarshan-intel**
## Description of the changes 
Add support for CentOS Stream 9 using the image - quay.io/centos/centos:stream9 to GSC.

## How to test this PR? 
To test this PR, set follow similar procedure as followed with Ubuntu and do gsc build and signing commands.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/205)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/205)* status: 0 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O31uVC2aaOmY5O_Qg:-O0O31uW3rxQTcAYabld:bk6phn5) (no related file):*
I'd like to request reviews from @jkr0103 and @anjalirai-intel

___
___
*[`gsc.py` line 264 at r1](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O28s62fnF0FPOMyed:-O0O28s7BYZ8c8GNqVJ6:b-6m7xmo) ([raw file](https://github.com/gramineproject/gsc/blob/9c8230dc6e3e76359b101ec03c66d470bf0c3047/gsc.py#L264)):*
> ```Python
> 
>     if (os_release['ID'] == 'centos'):
>         distro = 'quay.io/centos/centos:stream' + version_id
> ```

Aren't you supposed to also check that `version_id == 9`? Otherwise it seems that your code will try to use `quay.io/centos/centos:stream8` even for CentOS 8.
___
*[`templates/quay.io/centos/centos/apploader.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O2ZLt5nF8P6tt0YM_:-O0O2ZLuExwJ36TuB6cw:b-dhdxde) ([raw file](https://github.com/gramineproject/gsc/blob/9c8230dc6e3e76359b101ec03c66d470bf0c3047/templates/quay.io/centos/centos/apploader.template#L1)):*
> ```
> {% extends "apploader.common.template" %}
> ```

Isn't this file exactly like `templates/centos/apploader.template`?

Please instead use the simple:
```
{% extends "centos/apploader.template" %}
```

See a similar example for Ubuntu: https://github.com/gramineproject/gsc/blob/master/templates/ubuntu/apploader.template. Recall that Ubuntu is derived from Debian, which is similar to CentOS Stream being derived from CentOS.
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O2owy4DJ1eXJbYOAm:-O0O2owy4DJ1eXJbYOAn:bn11vyu) ([raw file](https://github.com/gramineproject/gsc/blob/9c8230dc6e3e76359b101ec03c66d470bf0c3047/templates/quay.io/centos/centos/Dockerfile.build.template#L1)):*
> ```
> {% extends "Dockerfile.common.build.template" %}
> ```

ditto for all these files -- can't they all be derived from `templates/centos/` files?
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 74 at r1](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O2y5S9ULUvj_66KTN:-O0O2y5S9ULUvj_66KTO:b-y55dks) ([raw file](https://github.com/gramineproject/gsc/blob/9c8230dc6e3e76359b101ec03c66d470bf0c3047/templates/quay.io/centos/centos/Dockerfile.compile.template#L74)):*
> ```
>         python3-scipy \
>         python3-voluptuous \
>         R-core \
> ```

Why do you have these random packages like R?

**Comment by adarshan-intel** [comment]
*[`gsc.py` line 264 at r1](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O28s62fnF0FPOMyed:-O0T8DqmDE2xZEYfS041:bs7wumb) ([raw file](https://github.com/gramineproject/gsc/blob/9c8230dc6e3e76359b101ec03c66d470bf0c3047/gsc.py#L264)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't you supposed to also check that `version_id == 9`? Otherwise it seems that your code will try to use `quay.io/centos/centos:stream8` even for CentOS 8.
</blockquote></details>

Done.

**Comment by adarshan-intel** [comment]
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 74 at r1](https://reviewable.io/reviews/gramineproject/gsc/205#-O0O2y5S9ULUvj_66KTN:-O0T8YqD7-N8D5yN0Dk5:b-1z3vz8) ([raw file](https://github.com/gramineproject/gsc/blob/9c8230dc6e3e76359b101ec03c66d470bf0c3047/templates/quay.io/centos/centos/Dockerfile.compile.template#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have these random packages like R?
</blockquote></details>

Removed unnecessary packages

**Comment by adarshan-intel** [comment]
Closing this PR as the branch name should follow this convention - name/feature.
Updated PR #206

**Pull request closed without merging**
