### PR TITLE
Replace Graphene with Gramine everywhere

### PR DESCRIPTION
**Pull request by dimakuv**
This includes using `github.com/gramineproject/gramine` link and changing executables from e.g. `graphene-sgx` to `gramine-sgx`.

**NOTE:** This depends on https://github.com/gramineproject/gramine/pull/17

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)

### CODE REVIEW

**Review by veenasai2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)* status: 0 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[templates/Dockerfile.ubuntu18.04.build.template, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqV7jBewabx5sXPD6:-MkLqV7jBewabx5sXPD7:b-z4rd2r) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L33)):*
> ```
> 
> # Copy Graphene runtime and signer tools to /graphene/meson_build_output
> RUN mkdir -p /graphene/Tools \
> ```

We don't need this now.
___
*[templates/Dockerfile.ubuntu18.04.build.template, line 37 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqcn6-vWRtzYyKT5K:-MkLqcn6-vWRtzYyKT5L:b-kczy29) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L37)):*
> ```
> 
> # TODO: remove this copy after argv_serializer becomes a part of Meson build
> COPY --from=graphene /graphene/Tools/argv_serializer /graphene/Tools
> ```

This can also be removed
___
*[templates/Dockerfile.ubuntu18.04.build.template, line 47 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqfucBcv-jpuz2z0g:-MkLqfucBcv-jpuz2z0h:b-jsnuml) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L47)):*
> ```
> # Generate trusted arguments if required
> {% if not insecure_args %}
> RUN /graphene/Tools/argv_serializer {{binary}} {{binary_arguments}} "{{"\" \"".join(cmd)}}" > /trusted_argv
> ```

This one should be /gramine/meson_build_output/bin/graphene-argv-serializer or /gramine/meson_build_output/bin/gramine-argv-serializer. 
___
*[templates/Dockerfile.ubuntu18.04.compile.template, line 19 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLpb3e4wpo27bkahYi:-MkLpb3e4wpo27bkahYj:b-i2an1z) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.compile.template#L19)):*
> ```
>         python3-protobuf \
>         wget \
>     && python3 -B -m pip install toml>=0.10
> ```

We need to add "pip meson ninja " to avoid meson version dependency error (>=0.55) and "Could not detect Ninja v1.8.2 or newer" error. Also, pkg-config should be installed  with "apt-get install pkg-config", otherwise meson build fails.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)* status: 0 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/10#-MkMMCk207tF04JtMTAL:-MkMMCk207tF04JtMTAM:bm06o2g) (no related file):*
@veenasai2 Thanks for the review, I will apply your comments when doing the rebase (today or next week).

---
___
*[templates/Dockerfile.ubuntu18.04.build.template, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqV7jBewabx5sXPD6:-MkMM11m4PtChSmfdX1F:bii0sde) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L33)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

We don't need this now.
</blockquote></details>

Thanks, I will rebase this PR later so that it uses proper steps

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)* status: 0 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/10#-MkMMCk207tF04JtMTAL:-MkNLm6C3GIJZucat93H:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 Thanks for the review, I will apply your comments when doing the rebase (today or next week).
</blockquote></details>

Done.

---
___
*[templates/Dockerfile.ubuntu18.04.build.template, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqV7jBewabx5sXPD6:-MkNM0hsAaskIJELz8dj:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, I will rebase this PR later so that it uses proper steps
</blockquote></details>

Done.
___
*[templates/Dockerfile.ubuntu18.04.build.template, line 37 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqcn6-vWRtzYyKT5K:-MkNBt2E65vzjlNhCSRN:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L37)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

This can also be removed
</blockquote></details>

Done.
___
*[templates/Dockerfile.ubuntu18.04.build.template, line 47 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLqfucBcv-jpuz2z0g:-MkNC5S61f2LisX9tVqV:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.build.template#L47)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

This one should be /gramine/meson_build_output/bin/graphene-argv-serializer or /gramine/meson_build_output/bin/gramine-argv-serializer. 
</blockquote></details>

Done.
___
*[templates/Dockerfile.ubuntu18.04.compile.template, line 19 at r1](https://reviewable.io/reviews/gramineproject/gsc/10#-MkLpb3e4wpo27bkahYi:-MkNCi8s4W7lXreTiWt4:bxqgxz7) ([raw file](https://github.com/gramineproject/gsc/blob/d79ea25af3fb3c908dc882a03bcdca8451ebe154/templates/Dockerfile.ubuntu18.04.compile.template#L19)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

We need to add "pip meson ninja " to avoid meson version dependency error (>=0.55) and "Could not detect Ninja v1.8.2 or newer" error. Also, pkg-config should be installed  with "apt-get install pkg-config", otherwise meson build fails. 
</blockquote></details>

Done. In a slightly different way (followed https://github.com/gramineproject/gramine/blob/master/.ci/ubuntu18.04.dockerfile)

**Review by veenasai2 — COMMENTED** [review]
Functionality-wise this PR works fine. Tested python-gsc image, ra-tls-secret-prov image, gsc with debug mode, all  are working fine. Thanks. 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10#-:-Mkaowfz6mJhTXcTktUS:bc1trng)* status: 0 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[templates/entrypoint.manifest.template, line 20 at r2](https://reviewable.io/reviews/gramineproject/gsc/10#-MkgBYZ58QVk7D5eO1TH:-MkgBYZ58QVk7D5eO1TI:bof8zs1) ([raw file](https://github.com/gramineproject/gsc/blob/dc8a70c48c818b97158d2b4033ca045ba323bfab/templates/entrypoint.manifest.template#L20)):*
> ```
> # !! INSECURE !! Allow passing command-line arguments from the host without validation.
> # Most Docker images rely on runtime arguments and hence, a more general technique is required.
> # The issue is documented at https://github.com/gramineproject/graphene/issues/1520.
> ```

Please update this to `https://github.com/gramineproject/gsc/issues/13`.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)* status: 9 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[templates/entrypoint.manifest.template, line 20 at r2](https://reviewable.io/reviews/gramineproject/gsc/10#-MkgBYZ58QVk7D5eO1TH:-MkgUbYJ9q0lg8OUOJ_b:but4bx4) ([raw file](https://github.com/gramineproject/gsc/blob/dc8a70c48c818b97158d2b4033ca045ba323bfab/templates/entrypoint.manifest.template#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please update this to `https://github.com/gramineproject/gsc/issues/13`.
</blockquote></details>

Done (using rebase, so we can merge quicker)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
