### PR TITLE
Remove Ubuntu 18.04 support

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

It was removed from Gramine v1.5.

## How to test this PR? 

Manually.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/156)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/156)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/156#-N_2qTME5_faO2KKhJno:-N_2qTME5_faO2KKhJnp:biyt4p) (no related file):*
Extracted from https://github.com/gramineproject/gsc/pull/155 as a separate stand-alone change. For easier reviewing. Kept Abin as the author.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/156)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/156#-N_2qjKHEmxgkNXYvorF:-N_2qjKHEmxgkNXYvorG:b-a0f9ln) (no related file):*
Manually verified that `ubuntu20.04-bash.dockerfile` and `ubuntu20.04-hello-world.dockerfile` tests work fine.

Note that the Python example currently fails. I will submit a separate PR shortly, that also fixes Python.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/156)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/156)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
