### PR TITLE
Bump Gramine version in GSC

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Same as these commits for previous `v1.3.1`:
- 065ad463d6e2ca02487573e900e83c89c8eb6b05
- eff9390bdfb57b1cb1f14ce28b22a65947768a19

**TODO**:
- [ ] After this PR is merged, I'll add a lightweight Git tag `v1.4` to this repo (on the first commit out of these two).

## How to test this PR? 

Test manually.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/132)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/132)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/132#-NOiwr077Pe7YfBG6Rwz:-NOiwr077Pe7YfBG6Rx-:biy900g) (no related file):*
@jinengandhi-intel: Could your team test this before we merge it as the official v1.4?

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/132)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/132#-NOiwr077Pe7YfBG6Rwz:-NOixXnx7GCNoru9j_ta:b-fbfutz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@jinengandhi-intel: Could your team test this before we merge it as the official v1.4?
</blockquote></details>

Yes, I asked them offline to test extensively. Let me also block on this, so that we don't merge this accidentally.

___

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/132)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/132#-NOiwr077Pe7YfBG6Rwz:-NOnNMjR2IEo9igJLsLs:b-9dzq58) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I asked them offline to test extensively. Let me also block on this, so that we don't merge this accidentally.
</blockquote></details>

I have verified both commits in the PR and they look good. No issues seen when running GSC tests on Ubuntu18/20 and CentOS.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/132)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/132#-NOiwr077Pe7YfBG6Rwz:-NOn_D3g6Ob9VioQznsi:b-t4ren7) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

I have verified both commits in the PR and they look good. No issues seen when running GSC tests on Ubuntu18/20 and CentOS.
</blockquote></details>

Thanks, resolving from my side. Waiting for @mkow's approval now.

___

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/132)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
