### PR TITLE
Remove stale tests and corresponding Makefile

### PR DESCRIPTION
**Pull request by dimakuv**
Most tests under `test/` don't work with newer Gramine because some corresponding applications (Node.js, PyTorch) were moved out of the core Gramine repo completely and other applications (Python, RA-TLS) need changes in their Dockerfiles. Note that previously GSC tests were tightly coupled with the core repo and assumed that `../../../Examples` contained all required files for tested examples; this is now false.

Therefore, this commit removes the tests dependent on the `Examples/` directory of the core repo. Instead, only self-contained tests are left. As a side effect, the overcomplicated and stale Makefile is not needed anymore and is removed. README is updated accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/7)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[test/README.rst, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/7#-MjnmfQm6GzckIs9D0nA:-MjnmH1e-uN7gAwutGMg:bi9a1o8) ([raw file](https://github.com/gramineproject/gsc/blob/b222421148ba1e36874627354d16d427fead4411/test/README.rst#L33)):*
> ```reStructuredText
>    docker build --tag ubuntu18.04-bash --file test/ubuntu18.04-bash.dockerfile .
> 
>    ./gsc build --insecure-args ubuntu18.04-bash test/ubuntu18.04-bash.manifest
> ```

Hmm, I get:
```
gsc build: error: argument -c/--config_file: can't open 'config.yaml': [Errno 2] No such file or directory: 'config.yaml'
```
here, if I follow these instructions. It's a bit weird, as this comment does not pass `-c` argument, which is optional...

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/7)* status: 15 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[test/README.rst, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/7#-MjnmfQm6GzckIs9D0nA:-Mk6GRqED_zBVcd5qDje:b4bmibb) ([raw file](https://github.com/gramineproject/gsc/blob/b222421148ba1e36874627354d16d427fead4411/test/README.rst#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I get:
```
gsc build: error: argument -c/--config_file: can't open 'config.yaml': [Errno 2] No such file or directory: 'config.yaml'
```
here, if I follow these instructions. It's a bit weird, as this comment does not pass `-c` argument, which is optional...
</blockquote></details>

Done. I added a note above. You need to have the `config.yaml` created -- otherwise GSC doesn't know from where to fetch Gramine and the SGX driver.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/7)* status: 15 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[test/README.rst, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/7#-MjnmfQm6GzckIs9D0nA:-Mk6GjVo-KXrChdCqdXy:bxqgt26) ([raw file](https://github.com/gramineproject/gsc/blob/b222421148ba1e36874627354d16d427fead4411/test/README.rst#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I added a note above. You need to have the `config.yaml` created -- otherwise GSC doesn't know from where to fetch Gramine and the SGX driver.
</blockquote></details>

`-c` argument is optional, but in this case GSC simply defaults to `config.yaml` filename.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/7)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[test/README.rst, line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/7#-MjnmfQm6GzckIs9D0nA:-Mk77VIf5IhUe-Ck7Hyz:b21i2eu) ([raw file](https://github.com/gramineproject/gsc/blob/b222421148ba1e36874627354d16d427fead4411/test/README.rst#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`-c` argument is optional, but in this case GSC simply defaults to `config.yaml` filename.
</blockquote></details>

Ah. That was confusing, thanks for updating the docs.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
