### PR TITLE
[Doc] Added venv for Ubuntu 24.04

### PR DESCRIPTION
**Pull request by adarshan-intel**
## Description of the changes 
- This PR is a temporary workaround for #202  and should be removed once the fix is upstreamed in the apt repo of Ubuntu 24.04

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XEOA72v8eNHoEnxVS):*
```
[Docs] Add venv workaround for Ubuntu 24.04

Ubuntu 24.04 has a bug that prevents running GSC out-of-the-box, see
https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348

Until this bug is fixed, users must prepare venv for GSC. Describe this.
```

___
*[`Documentation/index.rst` line 57 at r1](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XCOfp9f1l6-eVVIwC:-O5XCOfq8cuUn4JRiIgp:b-we1u4q) ([raw file](https://github.com/gramineproject/gsc/blob/2836f83158d9c6d5b63418616537250ad6200420/Documentation/index.rst#L57)):*
> ```reStructuredText
>    pip3 install docker jinja2 tomli tomli-w pyyaml
> 
> On Ubuntu 24.04 (and any recent distro compliant with PEP 668) use Python virtual
> ```

This should be slightly different:
```
Python venv workaround for Ubuntu 24.04
---------------------------------------

Unfortunately, Ubuntu 24.04 (noble) has a `bug that prevents out-of-the-box
execution of
GSC<https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348>`__.

Until this bug is fixed, GSC must be run on Ubuntu 24.04 via Python virtual
environment (venv). Please perform the following steps to install and activate
venv for GSC:

.. code-block:: sh

   sudo apt-get install python3-venv
   python3 -m venv my_venv && source my_venv/bin/activate
   pip3 install 'docker>=6.1.0' jinja2 tomli tomli-w pyyaml

Now you can execute GSC commands (`gsc build`, `gsc sign`, etc.) as usual,
within the virtual environment confines.
```

**Review by adarshan-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XEOA72v8eNHoEnxVS):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
[Docs] Add venv workaround for Ubuntu 24.04

Ubuntu 24.04 has a bug that prevents running GSC out-of-the-box, see
https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348

Until this bug is fixed, users must prepare venv for GSC. Describe this.
```

</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 57 at r1](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XCOfp9f1l6-eVVIwC:-O5XLsWp88yXm0XKVDoB:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2836f83158d9c6d5b63418616537250ad6200420/Documentation/index.rst#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be slightly different:
```
Python venv workaround for Ubuntu 24.04
---------------------------------------

Unfortunately, Ubuntu 24.04 (noble) has a `bug that prevents out-of-the-box
execution of
GSC<https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348>`__.

Until this bug is fixed, GSC must be run on Ubuntu 24.04 via Python virtual
environment (venv). Please perform the following steps to install and activate
venv for GSC:

.. code-block:: sh

   sudo apt-get install python3-venv
   python3 -m venv my_venv && source my_venv/bin/activate
   pip3 install 'docker>=6.1.0' jinja2 tomli tomli-w pyyaml

Now you can execute GSC commands (`gsc build`, `gsc sign`, etc.) as usual,
within the virtual environment confines.
```
</blockquote></details>

Done.

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`Documentation/index.rst` line 62 at r2](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XRiC82m5ivR6EgK9d:-O5XRiC82m5ivR6EgK9e:b-dvfzuy) ([raw file](https://github.com/gramineproject/gsc/blob/1e9c88503c2925beea5ff9e5cbebbb1c4866bce5/Documentation/index.rst#L62)):*
> ```reStructuredText
> Unfortunately, Ubuntu 24.04 (noble) has a `bug that prevents out-of-the-box
> execution of
> GSC<https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348>`__.
> ```

I think a space is needed here -> `GSC <`



_Code quote:_
```reStructuredText
GSC<
```

**Review by adarshan-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/index.rst` line 62 at r2](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XRiC82m5ivR6EgK9d:-O5XTXK1CJ9XWI-RA1pX:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1e9c88503c2925beea5ff9e5cbebbb1c4866bce5/Documentation/index.rst#L62)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think a space is needed here -> `GSC <`
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 62 at r2](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XRiC82m5ivR6EgK9d:-O5XWuNPCDB4OHs4omvC:bzcej7m) ([raw file](https://github.com/gramineproject/gsc/blob/1e9c88503c2925beea5ff9e5cbebbb1c4866bce5/Documentation/index.rst#L62)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, the space is not needed, as this is the hyperlink syntax of RestructuredText. Please revert this change (or explain to me why this is necessary).

**Review by adarshan-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/index.rst` line 62 at r2](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XRiC82m5ivR6EgK9d:-O5XZXnD8pOtd1s-TWZL:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1e9c88503c2925beea5ff9e5cbebbb1c4866bce5/Documentation/index.rst#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, the space is not needed, as this is the hyperlink syntax of RestructuredText. Please revert this change (or explain to me why this is necessary).
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 62 at r2](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XRiC82m5ivR6EgK9d:-O5XcHUyAK3f9QK1lEad:b-7ikepx) ([raw file](https://github.com/gramineproject/gsc/blob/1e9c88503c2925beea5ff9e5cbebbb1c4866bce5/Documentation/index.rst#L62)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was wrong, sorry: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#hyperlinks

Indeed, there needs to be a space after `GSC`... Sorry, please do it again, as Kailun requested.

**Review by adarshan-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 62 at r2](https://reviewable.io/reviews/gramineproject/gsc/214#-O5XRiC82m5ivR6EgK9d:-O5l8G4B89O0DCVPNyKE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1e9c88503c2925beea5ff9e5cbebbb1c4866bce5/Documentation/index.rst#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I was wrong, sorry: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#hyperlinks

Indeed, there needs to be a space after `GSC`... Sorry, please do it again, as Kailun requested.
</blockquote></details>

Done.

**Comment by adarshan-intel** [comment]
@woju Please review this PR.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/214)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
