### PR TITLE
Improve error message on failed TOML parsing

### PR DESCRIPTION
**Pull request by jkr0103**
## Description of the changes 

In case of errors while parsing the files with `tomli.loads`, error doesn't indicate the filename in which parsing failed.

This PR add the source of error.

## How to test this PR? 

Induce syntax error in user manifest and verify.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfRtsI3OrJtJlDjUzb:-NhfRtsI3OrJtJlDjUzc:bpui0o0) (no related file):*
@jkr0103 Can you show the logs/snippets how the messages look like without this PR and with this PR?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSugI3qOgcguU5AgC):*
I would change to `Improve error message on failed TOML parsing`
___
*[`gsc.py` line 243 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSYil9XMf-SSMVyRZ:-NhfSYil9XMf-SSMVyR_:b-xyfxz3) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L243)):*
> ```Python
>         entrypoint_manifest_dict = tomli.loads(entrypoint_manifest_render)
>     except Exception as e:
>         print(f'Failed to parse the \"{distro}/entrypoint.manifest.template\" file. Error:', e)
> ```

Do you really need the `\` escape symbols here? I thought you don't.
___
*[`gsc.py` line 247 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSdhxEd94lY-B9l_A:-NhfSdhxEd94lY-B9l_B:b-7px81b) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L247)):*
> ```Python
> 
>     base_image_environment = extract_environment_from_image_config(original_image.attrs['Config'])
>     try:
> ```

I don't think you need this try-except block here, because this `base_image_environment` TOML is generated by ourselves. So we should never fail, since we create this TOML ourselves. I suggest to revert.
___
*[`gsc.py` line 255 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSL5r5BvjCt3-1Zuf:-NhfSL5r5BvjCt3-1Zug:b-vwk67z) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L255)):*
> ```Python
>     user_manifest_contents = ''
>     if not os.path.exists(args.manifest):
>         print(f'Manifest file {args.manifest} does not exist')
> ```

Why did you modify this place? For uniformity?
___
*[`gsc.py` line 263 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSpuc8__zn5prXlIg:-NhfSpuc8__zn5prXlIh:bsfsvjg) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L263)):*
> ```Python
>             user_manifest_dict = tomli.loads(user_manifest_contents)
>         except Exception as e:
>             print(f'Failed to parse the \"{args.manifest}\" file. Error:', e)
> ```

ditto (really need `\`?)

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfRtsI3OrJtJlDjUzb:-NhfgELhBSW-5Ze_aYfc:b47cwe0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@jkr0103 Can you show the logs/snippets how the messages look like without this PR and with this PR?
</blockquote></details>

Erro message without this PR:



_Code snippet (i):_
```

Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "/home/intel/jk/gsc-sgx-sign/./gsc.py", line 562, in main
    return args.command(args)
  File "/home/intel/jk/gsc-sgx-sign/./gsc.py", line 257, in gsc_build
    user_manifest_dict = tomli.loads(user_manifest_contents)
  File "/usr/lib/python3/dist-packages/tomli/_parser.py", line 123, in loads
    raise suffixed_err(
tomli.TOMLDecodeError: Expected newline or end of document after a statement (at line 7, column 26)



Error Message with PR:
```



_Code snippet (ii):_
```
Failed to parse the "redis.manifest" file. Error: Expected newline or end of document after a statement (at line 7, column 26)
```

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSugI3qOgcguU5AgC):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would change to `Improve error message on failed TOML parsing`
</blockquote></details>

Done.
___
*[`gsc.py` line 243 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSYil9XMf-SSMVyRZ:-NhfgpfAD-tMgEbmAQeA:b-8a0yvn) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you really need the `\` escape symbols here? I thought you don't.
</blockquote></details>

Correct, `\` not required.
___
*[`gsc.py` line 247 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSdhxEd94lY-B9l_A:-NhfgxAW557hOCoaRIyo:bss4a2b) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L247)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think you need this try-except block here, because this `base_image_environment` TOML is generated by ourselves. So we should never fail, since we create this TOML ourselves. I suggest to revert.
</blockquote></details>

Removed.
___
*[`gsc.py` line 255 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSL5r5BvjCt3-1Zuf:-Nhfgz823Zt2nIHzssDk:bp59hqr) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you modify this place? For uniformity?
</blockquote></details>

Actually not for uniformity but by design applications should not crash with exceptions, application should handle the exceptions and take appropriate action and exit gracefully. It looked unnecessary to raise exception here and crash the application.

Please see the difference in messages before and after the PR.

Error message before PR:



_Code snippet (i):_
```Python
Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "/home/intel/jk/gsc-sgx-sign/./gsc.py", line 561, in main
    return args.command(args)
  File "/home/intel/jk/gsc-sgx-sign/./gsc.py", line 251, in gsc_build
    raise FileNotFoundError(f'Manifest file {args.manifest} does not exist')
FileNotFoundError: Manifest file redis.manifest does not exist



Error message after PR:
    
```



_Code snippet (ii):_
```Python
Manifest file redis.manifest does not exist
```
___
*[`gsc.py` line 263 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSpuc8__zn5prXlIg:-NhfhgCD4JOXfWiBYaj1:bvg4xkm) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L263)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (really need `\`?)
</blockquote></details>

not needed, hence removed.

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 255 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSL5r5BvjCt3-1Zuf:-NhfiTIT0H8j9W4TkS5c:b-eepon4) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L255)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Actually not for uniformity but by design applications should not crash with exceptions, application should handle the exceptions and take appropriate action and exit gracefully. It looked unnecessary to raise exception here and crash the application.

Please see the difference in messages before and after the PR.

Error message before PR:
</blockquote></details>

Shell we prefix `Error: ` to this message like:

`print(f'Error: Manifest file {args.manifest} does not exist')`

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfRtsI3OrJtJlDjUzb:-NhfpEQ00Y1WQBAU3scV:bi4tqaf) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Erro message without this PR:
</blockquote></details>

Nice. Looks good to me, thanks.

___
___
*[`gsc.py` line 255 at r1](https://reviewable.io/reviews/gramineproject/gsc/176#-NhfSL5r5BvjCt3-1Zuf:-Nhfp_uu1eSVSbPvgF0m:bg3b8t5) ([raw file](https://github.com/gramineproject/gsc/blob/8a7f0faa72580c7f093ce57d0a13bcea9b35f8e2/gsc.py#L255)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Shell we prefix `Error: ` to this message like:

`print(f'Error: Manifest file {args.manifest} does not exist')`
</blockquote></details>

No, I wouldn't add the prefix `Error:` here.

But please add a dot at the end of the sentence, for uniformity with other messages (see other places in this file).

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`gsc.py` line 244 at r3](https://reviewable.io/reviews/gramineproject/gsc/176#-Nhg1XgA-8g-0jsgqtsg:-Nhg1XgA-8g-0jsgqtsh:b-t01ldn) ([raw file](https://github.com/gramineproject/gsc/blob/caaa1b7bc2d4b883980d237b518188b01c9dd678/gsc.py#L244)):*
> ```Python
>     except Exception as e:
>         print(f'Failed to parse the "{distro}/entrypoint.manifest.template" file. Error:', e)
>         sys.exit(1)
> ```

I suggest to print to stderr by `print(..., file=sys.stderr)` as we consider this fatal and will simply exit if it happens.



_Code quote:_
```Python
        print(f'Failed to parse the "{distro}/entrypoint.manifest.template" file. Error:', e)
        sys.exit(1)
```
___
*[`gsc.py` line 251 at r3](https://reviewable.io/reviews/gramineproject/gsc/176#-Nhg2_fi9l7BD2cEqM6i:-Nhg2_fjB_j9Puq8-cfB:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/caaa1b7bc2d4b883980d237b518188b01c9dd678/gsc.py#L251)):*
> ```Python
>     user_manifest_contents = ''
>     if not os.path.exists(args.manifest):
>         print(f'Manifest file {args.manifest} does not exist.')
> ```

ditto
___
*[`gsc.py` line 259 at r3](https://reviewable.io/reviews/gramineproject/gsc/176#-Nhg2ad48b5ssC_xofE9:-Nhg2ad48b5ssC_xofEA:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/caaa1b7bc2d4b883980d237b518188b01c9dd678/gsc.py#L259)):*
> ```Python
>             user_manifest_dict = tomli.loads(user_manifest_contents)
>         except Exception as e:
>             print(f'Failed to parse the "{args.manifest}" file. Error:', e)
> ```

ditto

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`gsc.py` line 243 at r4](https://reviewable.io/reviews/gramineproject/gsc/176#-Nhg6XTsCIC8lqR81kma:-Nhg6XTsCIC8lqR81kmb:bl3aljx) ([raw file](https://github.com/gramineproject/gsc/blob/3eaa173b92e040dac3e758a6e02ca93831dfc058/gsc.py#L243)):*
> ```Python
>         entrypoint_manifest_dict = tomli.loads(entrypoint_manifest_render)
>     except Exception as e:
>         print(f'Failed to parse the "{distro}/entrypoint.manifest.template" file. Error:', e, file=sys.stderr)
> ```

Pls wrap to 100 chars.



_Code quote:_
```Python
        print(f'Failed to parse the "{distro}/entrypoint.manifest.template" file. Error:', e, file=sys.stderr)
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`gsc.py` line 244 at r5](https://reviewable.io/reviews/gramineproject/gsc/176#-NhjiYdW6fcfQMSM_bK6:-NhjiYdW6fcfQMSM_bK7:b-cb71gt) ([raw file](https://github.com/gramineproject/gsc/blob/6878e379de1f54f5dff47bb7371c03d748a2f641/gsc.py#L244)):*
> ```Python
>     except Exception as e:
>         print(f'Failed to parse the "{distro}/entrypoint.manifest.template" file. Error:', e,
>               file=sys.stderr)
> ```

Technically we should do this `file=sys.stderr` everywhere in this (and `finalize_manifest.py`) main func.

But this is out of scope of this PR.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/176)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
