### PR TITLE
Update to v1.8

### PR DESCRIPTION
**Pull request by adarshan-intel**
## Description of the changes 
Now that Gramine will have a new version v1.8, update GSC.

This PR follows the pattern in https://github.com/gramineproject/gsc/pull/198

Prerequisite: Gramine tagged with v1.8

## How to test this PR? 
As usual

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)

### CODE REVIEW

**Review by jkr0103 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218#-:-O9JN3FnECqqx7HDrr7l:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/218#-O9OGIIK7pz0pCyNmhxX:-O9OGIIK7pz0pCyNmhxY:bazif6r) (no related file):*
Note to other reviewers: don't be surprised by empty diff in Reviewable. Please review commit by commit (cannot be chosen in Reviewable any more for this PR, unfortunately).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/218#-O9OGRcNCdECis3UoLBg:-O9OGRcNCdECis3UoLBh:b-ued5fd) (no related file):*
This should be merged after #217 . Blocking.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/218#-O9OGRcNCdECis3UoLBg:-O9nTTtz7jTOrvyHnnor:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be merged after #217 . Blocking.
</blockquote></details>

Done.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/218)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
