### PR TITLE
Build with Dcap options enabled by default

### PR DESCRIPTION
**Pull request by aneessahib**
Build with Dcap options enabled by default., and point GSC to last stable release.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @aneessahib)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkIUO-32DtaSc7gSG):*
Why this error happens? This makes no sense, Redis image must contain `libcurl.so` if Redis uses it.

Or is `libcurl.so` needed for Gramine? I guess this is what you really mean: libcurl is needed for Gramine to perform EPID/DCAP attestation.
___
*[`config.yaml.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjQyh5uZ4uGsuummO:-N5EjQyi4lEeCFQGCqw8:b-uoxvip) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/config.yaml.template#L10)):*
> ```
> 
> # If you're using your own fork and branch of Gramine, specify the GitHub link and the branch name
> # below; typically, you want to keep the default values though, pointing to the stable release commit
> ```

I think you can revert this addition, it will be obvious with `v1.2`
___
*[`config.yaml.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjNQmBf37UgoOmQT1:-N5EjNQnARyC5OWm7cYy:b-xpkdli) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/config.yaml.template#L13)):*
> ```
> Gramine:
>     Repository: "https://github.com/gramineproject/gramine.git"
>     Branch:     "fd2e30274a2c0eb5aa7f9b95938f185345965eb4"
> ```

You can simply write here `"v1.2"`
___
*[`templates/centos/Dockerfile.compile.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkgJwAUx_RBp_gd2D:-N5EkgJx1E3t0q9o3iWJ:b9efoes) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L20)):*
> ```
>         git \
>         httpd \
>         libcurl-devel \
> ```

Ah, I see that libcurl is here already.
___
*[`templates/centos/Dockerfile.compile.template` line 41 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkmshCtbBoICqkG6v:-N5EkmshCtbBoICqkG6w:bva9lqi) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L41)):*
> ```
> 
> RUN mkdir /opt/intel && cd /opt/intel \
>     && wget https://download.01.org/intel-sgx/latest/linux-latest/distro/rhel8.4-server/sgx_rpm_local_repo.tgz \
> ```

This feels wrong to me. You're downloading from the RHEL 8.4 repository here, even if we build Gramine in e.g. CentOS 8. Does this work in your tests?

@woju Is this normal practice?
___
*[`templates/centos/Dockerfile.compile.template` line 47 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5ElEUyByOJyaTXdRgH:-N5ElEUyByOJyaTXdRgI:bheudkl) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L47)):*
> ```
>     && dnf -y --nogpgcheck --repofrompath=SGX,/opt/intel/sgx_rpm_local_repo install libsgx-dcap-quote-verify
> 
> RUN ln -s /usr/lib64/libsgx_dcap_quoteverify.so.1 /usr/lib64/libsgx_dcap_quoteverify.so
> ```

FYI: This is a bug in the `sgx_dcap_quoteverify` package -- it doesn't create the symlink, so we have to create it manually.
___
*[`templates/ubuntu/Dockerfile.build.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5Eka7HBENM_40qKoD3:-N5Eka7I3WV1cjFO9uxJ:bl1n118) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.build.template#L7)):*
> ```
>     && env DEBIAN_FRONTEND=noninteractive apt-get install -y \
>         binutils \
>         libcurl4-openssl-dev \
> ```

You added libcurl in Ubuntu, but what about CentOS? UPDATE: Ok, it was already there in CentOS.
___
*[`templates/ubuntu/Dockerfile.compile.template` line 27 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjnUM2b3P75XU3T7X:-N5EjnUM2b3P75XU3T7Y:b-pr323i) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.compile.template#L27)):*
> ```
>     && /usr/bin/python3 -B -m pip install 'toml>=0.10' 'meson>=0.55'
> 
> RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' \
> ```

This feels wrong to me. You're adding the `ubuntu bionic` (Ubuntu 18.04) repository here, even if we build Gramine in e.g. Ubuntu 20.04 or 22.04. Does this work in your tests?

@woju Is this normal practice? Could the repository for one version be re-used in another version?
___
*[`templates/ubuntu/Dockerfile.compile.template` line 32 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkB8W1Sdsuad202gh:-N5EkB8X01Xwt6QG8DVV:b-r279xn) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.compile.template#L32)):*
> ```
>     && apt-key add intel-sgx-deb.key
> 
> RUN apt-get update && apt-get install -y libsgx-dcap-quote-verify-dev
> ```

We also add `env DEBIAN_FRONTEND=noninteractive` before running apt commands (see the example above), please do the same

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @aneessahib)

___
*[`templates/centos/Dockerfile.compile.template` line 47 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5ElEUyByOJyaTXdRgH:-N5FBwTX7lzO9XYGfhtQ:b-tao67u) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This is a bug in the `sgx_dcap_quoteverify` package -- it doesn't create the symlink, so we have to create it manually.
</blockquote></details>

This ^ should be a comment in the code.

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: 1 of 7 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkIUO-32DtaSc7gSG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this error happens? This makes no sense, Redis image must contain `libcurl.so` if Redis uses it.

Or is `libcurl.so` needed for Gramine? I guess this is what you really mean: libcurl is needed for Gramine to perform EPID/DCAP attestation.
</blockquote></details>

Sorry - Should have been clearer. Yes this is needed for attestation only, and this will have to be done for any gsc image if we wish to add attestation as well. 
___
*[`config.yaml.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjQyh5uZ4uGsuummO:-N5aTW7FAsFXyCPK3SsB:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/config.yaml.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you can revert this addition, it will be obvious with `v1.2`
</blockquote></details>

Done.
___
*[`config.yaml.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjNQmBf37UgoOmQT1:-N5aTWVk3z7XBOWg2VOm:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/config.yaml.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can simply write here `"v1.2"`
</blockquote></details>

Done.
___
*[`templates/ubuntu/Dockerfile.compile.template` line 29 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5Kn1xD9hiXQpyqBftd:-N5aToRG9TNjPTQIf0LU:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.compile.template#L29)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Don't download, please commit the file to the repository and `COPY` it into the container.
</blockquote></details>

Done.
___
*[`templates/ubuntu/Dockerfile.compile.template` line 32 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkB8W1Sdsuad202gh:-N5aToyNEvzI3iFcHe1Y:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.compile.template#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This, or add global `ENV`.
</blockquote></details>

Done.
___
*[`templates/centos/Dockerfile.compile.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkgJwAUx_RBp_gd2D:-N5aTqf_2DnN8o6by44j:btn2gqf) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I see that libcurl is here already.
</blockquote></details>

This is in the compile template. We are adding it to the build template, so that the final GSC image has it.
___
*[`templates/centos/Dockerfile.compile.template` line 45 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5KkrF76BWILUbDUhRe:-N5aU1D0B_zvXAHOY1fc:b-fpzga5) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L45)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Normal practice would be to have regular yum repository available via HTTP, addded with proper gpg key which we would`COPY` in Dockerfile from our repository, and not "local repo" unpacked from tarball. I object to this `--nogpgcheck`, because right now it relies on HTTPS to guarantee integrity of this sgx repo. Unless and until Intel provides a signed, online YUM repo, I don't see this merged.

Our regular packages, which don't have `-Ddcap` for this exact reason. If we had this yum repo, I could just build the packages with DCAP libs enabled and we could install packages from our regular repo.

We can rebuild the packages any time Intel provides the repo without a new version of gramine, I can just make a new package revision.
</blockquote></details>

Ok, not doing -Ddcap for centos
___
*[`templates/centos/Dockerfile.compile.template` line 47 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5ElEUyByOJyaTXdRgH:-N5aU6hx0eBfB8KmQ9iS:bkgb2f4) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L47)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Better yet, it should be fixed in the package proper.
</blockquote></details>

Removed this for centos

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: 1 of 7 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`templates/ubuntu/Dockerfile.compile.template` line 27 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjnUM2b3P75XU3T7X:-N5aUbEOCDc4x2fMPs1G:b2nhb2c) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.compile.template#L27)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This depends on what's inside the repo and linking details. Because it's generally is OK to use ELFs compiled against older glibc on a system with newer glibc, so assuming there aren't any other linkages against sonames not present in newer system, it *generally*, *most of the time* should be OK. For example, our own repo is good to use on a range of debian-like distributions (currently Ubuntu 18.04-20.04 and Debian 11).
</blockquote></details>

Ack
___
*[`templates/centos/Dockerfile.compile.template` line 41 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkmshCtbBoICqkG6v:-N5aUglO0BeHQCEF4b1-:b2nhb2c) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Regarding RHEL8 vs CentOS 8 (or any other RHEL-derived distro like AlmaLinux), this is very much OK and lands squarely within ABI compatibility promised by CentOS (or said other derivatives). This is pretty much core promise of those binary-compatible RHEL recompilations, so if it doesn't, there's a big problem with upstream distro, to the point of questioning the viability of the whole project. I wouldn't worry about it at all.

But: see blocker below.
</blockquote></details>

Ack

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @mkow, and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EkIUO-32DtaSc7gSG):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Sorry - Should have been clearer. Yes this is needed for attestation only, and this will have to be done for any gsc image if we wish to add attestation as well. 
</blockquote></details>

I'll keep a blocking comment to rephrase it during final rebase.
___
*[`gsc.py` line 236 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iMoDyCr1veIHOhcHr:-N5iMoDz7rcavt4rM60s:b-nbtx89) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/gsc.py#L236)):*
> ```Python
> 
>     # Intel SGX PGP key to be added within graminized Docker image
>     shutil.copyfile('intel-sgx-deb.key', tmp_build_path / 'intel-sgx-deb.key')
> ```

You'll need to change to
```
    shutil.copyfile('templates/intel-sgx-deb.key', tmp_build_path / 'intel-sgx-deb.key')
```
___
*[`intel-sgx-deb.key` line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iMdPI0IADG5I4fr3r:-N5iMdPI0IADG5I4fr3s:b9so7o) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/intel-sgx-deb.key#L1)):*
> ```
> -----BEGIN PGP PUBLIC KEY BLOCK-----
> ```

Now we have some random file under the root dir of GSC. This is not user-friendly.

Let's move this file under `templates/`. It more logically belongs there.
___
*[`templates/Dockerfile.common.compile.template` line 33 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iM80fAl1Orz75TUxT:-N5iM80fAl1Orz75TUxU:b-ttkn4p) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/templates/Dockerfile.common.compile.template#L33)):*
> ```
>        --buildtype={% if debug %}debug{% else %}release{% endif %} \
>        -Ddirect=enabled -Dsgx=enabled \
>        {% if not "centos:8" in Distro %}-Ddcap=enabled{% endif %} \
> ```

This hard-codes the exact version of CentOS. Could we do this:
```
{% if not Distro.startswith('ubuntu') %}
```

This makes our logic more clear: "we only support DCAP for Ubuntu, any version".

But please check that this if-conditional actually works, I wrote it from memory. (I am not good at this Jinja2 templating.)
___
*[`templates/ubuntu/Dockerfile.compile.template` line 27 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5EjnUM2b3P75XU3T7X:-N5iKCyAASCtlBjmdYXo:bbkqx29) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/ubuntu/Dockerfile.compile.template#L27)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Ack
</blockquote></details>

Ok, then I'm ok with this `bionic`.
___
*[`templates/centos/Dockerfile.compile.template` line 45 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5KkrF76BWILUbDUhRe:-N5iKnooA42RVr0qyowO:b-6mnjq3) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L45)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Ok, not doing -Ddcap for centos
</blockquote></details>

This sounds good to me. Let's only do `-Ddcap` for Debian/Ubuntu for now.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @mkow, and @woju)

___
*[`gsc.py` line 235 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iRnjwCYhfu1CcPklV:-N5iRnjx6kZSfgdXGhE5:bdv7306) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/gsc.py#L235)):*
> ```Python
>     shutil.copyfile('finalize_manifest.py', tmp_build_path / 'finalize_manifest.py')
> 
>     # Intel SGX PGP key to be added within graminized Docker image
> ```

Please rephrase like this:
```
    # Intel's SGX PGP RSA-1024 key signing the intel-sgx/sgx_repo repository. Expires 2023-05-24.
    # Available at https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
```

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: 4 of 7 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, and @woju)

___
*[`gsc.py` line 235 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iRnjwCYhfu1CcPklV:-N5iamh70_5ug89GjOIF:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/gsc.py#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rephrase like this:
```
    # Intel's SGX PGP RSA-1024 key signing the intel-sgx/sgx_repo repository. Expires 2023-05-24.
    # Available at https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
```
</blockquote></details>

Done.
___
*[`gsc.py` line 236 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iMoDyCr1veIHOhcHr:-N5iawqtDlAWvatyhROo:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/gsc.py#L236)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You'll need to change to
```
    shutil.copyfile('templates/intel-sgx-deb.key', tmp_build_path / 'intel-sgx-deb.key')
```
</blockquote></details>

Done.
___
*[`templates/Dockerfile.common.compile.template` line 33 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iM80fAl1Orz75TUxT:-N5i_pdD8ksS4_VZ5woG:b-uh3mxp) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/templates/Dockerfile.common.compile.template#L33)):*
> {% if not Distro.startswith('ubuntu') %}
Looks good except for a small one :)
___
*[`templates/centos/Dockerfile.compile.template` line 45 at r1](https://reviewable.io/reviews/gramineproject/gsc/70#-N5KkrF76BWILUbDUhRe:-N5ib-SC03c3gLY-Dqv5:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f58e40439a7c89e98eda51539a19ee9035dc8b02/templates/centos/Dockerfile.compile.template#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sounds good to me. Let's only do `-Ddcap` for Debian/Ubuntu for now.
</blockquote></details>

Done.
___
*[`intel-sgx-deb.key` line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iMdPI0IADG5I4fr3r:-N5iay8z0kNEak8Y-Kx6:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/intel-sgx-deb.key#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now we have some random file under the root dir of GSC. This is not user-friendly.

Let's move this file under `templates/`. It more logically belongs there.
</blockquote></details>

Done.

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: 4 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, and @woju)

___
*[`intel-sgx-deb.key` line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iMdPI0IADG5I4fr3r:-N5kMSLY1pvKSk0PaRPy:b9kudgi) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/intel-sgx-deb.key#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, `templates/` is for templates in jinja (so they can be `{% include %}`d). If you don't want it in root of the repo, then please create a subdirectory (like `keys/`).
</blockquote></details>

Makes sense. Done

**Review by woju — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/gramineproject/gsc/70#-N5oJtu17we__plXUluR):*
I'll merge the next commit ("Fix for ...") into this second one, since they belong together (adding attestation capability).

Also, the commit message should mention that this is currently only for Ubuntu distros, because there is currently no package for `libsgx-dcap-quote-verify-dev` in CentOS.
___
*[`templates/Dockerfile.common.compile.template` line 33 at r3](https://reviewable.io/reviews/gramineproject/gsc/70#-N5iM80fAl1Orz75TUxT:-N5oJOCH8h_wO73YU2wy:b-jhqpuc) ([raw file](https://github.com/gramineproject/gsc/blob/e0df6df4646b329299c2f53ab1e578d524710c94/templates/Dockerfile.common.compile.template#L33)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

> {% if not Distro.startswith('ubuntu') %}
Looks good except for a small one :)
</blockquote></details>

Yeah, thanks, it was my blooper.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/gramineproject/gsc/70#-N5oJtu17we__plXUluR):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll merge the next commit ("Fix for ...") into this second one, since they belong together (adding attestation capability).

Also, the commit message should mention that this is currently only for Ubuntu distros, because there is currently no package for `libsgx-dcap-quote-verify-dev` in CentOS.
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 1 of 3 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/70)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
