### PR TITLE
Remove stale AKS-image Dockerfile and corresponding Makefile

### PR DESCRIPTION
**Pull request by dimakuv**
The AKS-image Dockerfile got stale and incorrect: it uses a very old out-of-tree DCAP SGX driver, it uses old Makefiles (no Meson) to build Graphene, and it was not tested since last year or so.

If anyone ever needs this, we will add it back (but I would postpone till Graphene is completely properly packaged, including all SGX utilities).

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/9)

### CODE REVIEW

**Comment by aneessahib** [comment]
Do we even need an images folder in GSC? All the images/dockerfiles etc should go into the relevant examples directory in GSC.  The ongoing AKS stuff also should go into Examples

**Review by dimakuv — COMMENTED** [review]
@aneessahib We don't need the `images/` folder, I agree. I want everything to be created/re-created in the correspoding `Examples/` sub-directory for each example. That's why this PR wants to remove these `images/` stuff completely.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/9#-:-MjTFGTeCsPQNmCDkcyk:b-akmgyc)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
