### PR TITLE
Add support to graminize docker images with Debian distro

### LINKED ISSUE #86: Add Debain 11 to the list of supported distros
## Description of the problem
The distro on the Redis docker image is debain 11 and providing `Debain11` to config.yaml.template doesn't result in any issues. So we should add Debain 11 as one of the supported distros.

### PR DESCRIPTION
**Pull request by aneessahib**
With this PR - GSC can support graminizing base images with Debian distro. No specific changes were needed to support to this. Ubuntu templates are reused as is.
Fixes #86 

To test, follow the below instructions:
1.  Create dockerfile  `debian11-bash.dockerfile` with the below contents

From debian:11
RUN apt-get update
CMD ["bash"]

2. `docker build --tag debian11-bash --file debian11-bash.dockerfile .`
3. `./gsc build --insecure-args debian11-bash test/generic.manifest`
4. `./gsc sign-image debian11-bash enclave-key.pem`
5. `docker run --device=/dev/sgx_enclave gsc-debian11-bash -c ls`

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
For other reviewers: this is a PR to fix https://github.com/gramineproject/gsc/issues/86. See discussions there.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89#-:-NCP2K2D7gg4MPY1UiHJ:b-4fq1yh)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP2Fbq3jN1nJySkLYg:-NCP2Fbq3jN1nJySkLYh:b-a0pmy8) (no related file):*
Please add to the PR description `Fixes #86`.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP3w1FBBX1WntXZRSe:-NCP3w1FBBX1WntXZRSf:b-nl4exd) (no related file):*
If all the files here are directly copy-pasted from the ones under `templates/ubuntu/`, I would strongly prefer them to be **symlinks** instead of files (with 100% duplicated content).

@mkow @boryspoplawski ?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP4B0M43w9flsUJUZj:-NCP4B0M43w9flsUJUZk:bddpk3t) (no related file):*
How to reproduce (test) this PR?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP2PQRAbgQIwCc3Jnf):*
I would simply say:
```
Add support for Debian distros

At least currently, Debian distro templates are exactly the same as
Ubuntu templates. Debian 10 and 11 were tested.
```

We can fix it during final rebase.
___
*[`config.yaml.template` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP2h501Isy_8aKVO6L:-NCP2h501Isy_8aKVO6M:b-ub07xo) ([raw file](https://github.com/gramineproject/gsc/blob/f7a60224b5d5824d7e3cc4554307265fb8cdb358/config.yaml.template#L3)):*
> ```
> # Specify the OS distro. Currently tested distros are
> # ``ubuntu:18.04``, ``ubuntu:20.04``, ``ubuntu:21.04``, ``debian:10``, ``debian11`` and
> # ``centos:8``.
> ```

I think at this point we need to reformat this comment. Like this:
```
# Specify the OS distro. Currently tested distros are:
#   - ubuntu:18.04, ubuntu:20.04, ubuntu:21.04
#   - debian:10, debian:11
#   - centos:8
```

(I don't remember/know why we had double-backticks in the names, they are not needed and only make it harder to read -- so I removed them in my new version of the comment)
___
*[`templates/debian/intel-sgx-deb.key` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP3fK95rVU24H3J1X3:-NCP3fK95rVU24H3J1X4:b-278h5b) ([raw file](https://github.com/gramineproject/gsc/blob/f7a60224b5d5824d7e3cc4554307265fb8cdb358/templates/debian/intel-sgx-deb.key#L11)):*
> ```
> UoYJ5PHswaihtdjNBFluU4pqrMk=
> =IvD4
> -----END PGP PUBLIC KEY BLOCK-----
> ```

This file is not used at all? We store the keys under https://github.com/gramineproject/gsc/blob/master/keys/ (`keys/`), and that's where we copy the key from.

So this file seems to be unused. Please remove it.

**Comment by woju** [comment]
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If all the files here are directly copy-pasted from the ones under `templates/ubuntu/`, I would strongly prefer them to be **symlinks** instead of files (with 100% duplicated content).

@mkow @boryspoplawski ?
</blockquote></details>

`{% extends %}` or `{% include %}` them?

Also, `ubuntu` is a derivative of `debian`, so it should be that ubuntu `{% extends %}` from debian.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP3w1FBBX1WntXZRSe:-NCPOFtpAvh7lOX8vztU:b-khz0pv) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`{% extends %}` or `{% include %}` them?

Also, `ubuntu` is a derivative of `debian`, so it should be that ubuntu `{% extends %}` from debian.
</blockquote></details>

@woju has a good point. Looks like we can modify all those Ubuntu templates to simply have `{% include %}`. @aneessahib Is this a good solution?

___

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: 5 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP2Fbq3jN1nJySkLYg:-NCQa2IfD5H8eivvEGLO:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add to the PR description `Fixes #86`.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP3w1FBBX1WntXZRSe:-NCQ_lq-CCDG3qnEPAob:bsd777v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju has a good point. Looks like we can modify all those Ubuntu templates to simply have `{% include %}`. @aneessahib Is this a good solution?
</blockquote></details>

Yes this is good. Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP4B0M43w9flsUJUZj:-NCQcpKsEVyeGblTo12V:b-fga1mq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How to reproduce (test) this PR?
</blockquote></details>

Added to PR description

___
___
*[`config.yaml.template` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP2h501Isy_8aKVO6L:-NCQ_yoQ08Qp3czzrKc-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f7a60224b5d5824d7e3cc4554307265fb8cdb358/config.yaml.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think at this point we need to reformat this comment. Like this:
```
# Specify the OS distro. Currently tested distros are:
#   - ubuntu:18.04, ubuntu:20.04, ubuntu:21.04
#   - debian:10, debian:11
#   - centos:8
```

(I don't remember/know why we had double-backticks in the names, they are not needed and only make it harder to read -- so I removed them in my new version of the comment)
</blockquote></details>

Done.
___
*[`templates/debian/intel-sgx-deb.key` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP3fK95rVU24H3J1X3:-NCQ_y87ACBxnP0X0-o-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f7a60224b5d5824d7e3cc4554307265fb8cdb358/templates/debian/intel-sgx-deb.key#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This file is not used at all? We store the keys under https://github.com/gramineproject/gsc/blob/master/keys/ (`keys/`), and that's where we copy the key from.

So this file seems to be unused. Please remove it.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP4B0M43w9flsUJUZj:-NCUTtUx40lQ5Mn6Qn03:b-85i5f9) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Added to PR description
</blockquote></details>

Thanks, I tested both Ubuntu-Python (to verify that normal, previous GSC works as usual) and Debian11-Bash (to verify the newly added functionality).

___
___
*[`config.yaml.template` line 3 at r2](https://reviewable.io/reviews/gramineproject/gsc/89#-NCUQ3EjE3RP_G6sHCSd:-NCUQ3EjE3RP_G6sHCSe:bau8m9o) ([raw file](https://github.com/gramineproject/gsc/blob/d201c59134ff2a94ec69c046477ce09f3bc87f13/config.yaml.template#L3)):*
> ```
> # Specify the OS distro. Currently tested distros are
> # - ubuntu:18.04, ubuntu:20.04, ubuntu:21.04
> # - debian:10, debian11
> ```

`debian11` -> `debian:11`

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: 11 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`config.yaml.template` line 3 at r2](https://reviewable.io/reviews/gramineproject/gsc/89#-NCUQ3EjE3RP_G6sHCSd:-NCUYXOC4dWlzj2rtw7k:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d201c59134ff2a94ec69c046477ce09f3bc87f13/config.yaml.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`debian11` -> `debian:11`
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`templates/debian/entrypoint.manifest.template` line 6 at r3](https://reviewable.io/reviews/gramineproject/gsc/89#-NCeAFt51wsg4YOP0kXY:-NCeAFt51wsg4YOP0kXZ:b-b5xtd9) ([raw file](https://github.com/gramineproject/gsc/blob/395a6c0118d0b725158e6628bb6d2395f448b571/templates/debian/entrypoint.manifest.template#L6)):*
> ```
> loader.entrypoint = "file:/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/libsysdb.so"
> 
> # ldconfig in Ubuntu 21.04 doesn't produce "/usr/lib/x86_64-linux-gnu" so add it explicitly
> ```

? This is a debian template?



_Code quote:_
```
Ubuntu 21.04
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`templates/debian/entrypoint.manifest.template` line 6 at r3](https://reviewable.io/reviews/gramineproject/gsc/89#-NCeAFt51wsg4YOP0kXY:-NCeEGzU0_jIBqY_a3ti:bz04aba) ([raw file](https://github.com/gramineproject/gsc/blob/395a6c0118d0b725158e6628bb6d2395f448b571/templates/debian/entrypoint.manifest.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

? This is a debian template?
</blockquote></details>

This probably also happens in Debian. I would test a Debian 11 (or whatever the latest one), check that without this trick it fails, and:
1. if it does fail, then update the comment (add `Debian 11/Ubuntu 21.04`)
2. If it doesn't fail, then create a separate entrypoing-template file under `ubuntu/` instead of the current `{{extends}}`

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`templates/debian/entrypoint.manifest.template` line 6 at r3](https://reviewable.io/reviews/gramineproject/gsc/89#-NCeAFt51wsg4YOP0kXY:-NCeFvxm5SXGXqso-Gse:b59200v) ([raw file](https://github.com/gramineproject/gsc/blob/395a6c0118d0b725158e6628bb6d2395f448b571/templates/debian/entrypoint.manifest.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This probably also happens in Debian. I would test a Debian 11 (or whatever the latest one), check that without this trick it fails, and:
1. if it does fail, then update the comment (add `Debian 11/Ubuntu 21.04`)
2. If it doesn't fail, then create a separate entrypoing-template file under `ubuntu/` instead of the current `{{extends}}`
</blockquote></details>

Instead, how about we simply state something like `Certain derivates of Debian (Ubuntu 21.04) doesn't produce ... ` ?

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`templates/debian/entrypoint.manifest.template` line 6 at r3](https://reviewable.io/reviews/gramineproject/gsc/89#-NCeAFt51wsg4YOP0kXY:-NCeI1_mB_Nf0pj6Y7fV:bps2xv3) ([raw file](https://github.com/gramineproject/gsc/blob/395a6c0118d0b725158e6628bb6d2395f448b571/templates/debian/entrypoint.manifest.template#L6)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Instead, how about we simply state something like `Certain derivates of Debian (Ubuntu 21.04) doesn't produce ... ` ?
</blockquote></details>

Btw - Only Ubuntu 21.04 does not produce this path with `ldconfig`. Debian 10/11 is fine. Shall we go with a generic messaging as I suggested above?

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`templates/debian/entrypoint.manifest.template` line 6 at r3](https://reviewable.io/reviews/gramineproject/gsc/89#-NCeAFt51wsg4YOP0kXY:-NCeM-nZ6C9kI353WD6i:b-p1vza1) ([raw file](https://github.com/gramineproject/gsc/blob/395a6c0118d0b725158e6628bb6d2395f448b571/templates/debian/entrypoint.manifest.template#L6)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Btw - Only Ubuntu 21.04 does not produce this path with `ldconfig`. Debian 10/11 is fine. Shall we go with a generic messaging as I suggested above? 
</blockquote></details>

I'd prefer @dimakuv's idea.

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: 10 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`templates/debian/entrypoint.manifest.template` line 6 at r3](https://reviewable.io/reviews/gramineproject/gsc/89#-NCeAFt51wsg4YOP0kXY:-NCehhlICfYCwLZZ2aG8:bon26yd) ([raw file](https://github.com/gramineproject/gsc/blob/395a6c0118d0b725158e6628bb6d2395f448b571/templates/debian/entrypoint.manifest.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer @dimakuv's idea.
</blockquote></details>

Done. `entrypoint.manifest.template` for Ubuntu like how it was. And removed the work-around from the Debian `entrypoint.manifest.template`.

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/89#-NCP2PQRAbgQIwCc3Jnf):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would simply say:
```
Add support for Debian distros

At least currently, Debian distro templates are exactly the same as
Ubuntu templates. Debian 10 and 11 were tested.
```

We can fix it during final rebase.
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/89)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
