### PR TITLE
Update GSC to support 20.04 Ubuntu containers

### PR DESCRIPTION
**Pull request by aneessahib**
Updates GSC to support 20.04 Ubuntu.

Fixes https://github.com/gramineproject/graphene/issues/2612

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)

### CODE REVIEW

**Comment by aneessahib** [comment]
resubmitted from https://github.com/gramineproject/graphene/pull/2670

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[test/Makefile, line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/14#-Mk6edqY-bHS5pBsgwiB:-Mk6edqY-bHS5pBsgwiC:b643yqj) ([raw file](https://github.com/gramineproject/gsc/blob/9674959c90d1c2294761c9e817a31fefe92468a1/test/Makefile#L8)):*
> ```Makefile
> 
> GRAPHENE_REPO ?= https://github.com/oscarlab/graphene.git
> GRAPHENE_BRANCH ?= "master"
> ```

We are removing this Makefile in another PR, so let's just revert the changes to this file in this PR.
___
*[test/README.rst, line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/14#-Mk6ehgO5xjlq9mkfkuP:-Mk6ehgO5xjlq9mkfkuQ:blwz93q) ([raw file](https://github.com/gramineproject/gsc/blob/9674959c90d1c2294761c9e817a31fefe92468a1/test/README.rst#L18)):*
> ```reStructuredText
> ``<distro>-<image-name>.manifest`` where ``<distro>`` specifies the underlying
> Linux distribution and ``<image-name>`` specifies the test case. The tests
> currently support Ubuntu 18.04 distribution only. The manifest
> ```

We are re-writing this README in another PR, so let's just revert the changes to this file in this PR.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[test/Makefile, line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/14#-Mk6edqY-bHS5pBsgwiB:-MkHWRtp3UBgnAZB15b8:b-zg4szk) ([raw file](https://github.com/gramineproject/gsc/blob/9674959c90d1c2294761c9e817a31fefe92468a1/test/Makefile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We are removing this Makefile in another PR, so let's just revert the changes to this file in this PR.
</blockquote></details>

Actually, already removed. Feel free to rebase this PR to the latest master of GSC repo.
___
*[test/README.rst, line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/14#-Mk6ehgO5xjlq9mkfkuP:-MkHWW2t6LXL1twsRjVX:b-zg4szk) ([raw file](https://github.com/gramineproject/gsc/blob/9674959c90d1c2294761c9e817a31fefe92468a1/test/README.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We are re-writing this README in another PR, so let's just revert the changes to this file in this PR.
</blockquote></details>

Actually, already removed. Feel free to rebase this PR to the latest master of GSC repo.

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[test/Makefile, line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/14#-Mk6edqY-bHS5pBsgwiB:-MkHvZHhAaVQAloFcxxQ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9674959c90d1c2294761c9e817a31fefe92468a1/test/Makefile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, already removed. Feel free to rebase this PR to the latest master of GSC repo.
</blockquote></details>

Done.
___
*[test/README.rst, line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/14#-Mk6ehgO5xjlq9mkfkuP:-MkHv_Ke6d28T95W-DeH:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9674959c90d1c2294761c9e817a31fefe92468a1/test/README.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, already removed. Feel free to rebase this PR to the latest master of GSC repo.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxYkoAbBAoO0NAnlI):*
By the way, we don't need to prepend `[GSC]` anymore -- we are already in the separate GSC repo, so it is obvious.

I will remove this during final rebase.
___
*[gsc.py, line 164 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxqE076_wOfICYKWQ:-MkHxqE076_wOfICYKWR:b2r1iak) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L164)):*
> ```Python
>     # generate Dockerfile.build from Jinja-style templates/Dockerfile.<distro>.build.template
>     # using the user-provided config file with info on OS distro, Graphene version and SGX driver
>     # and other env configurations generated above
> ```

The comment is wrong now. Please remove `distro` mentions.
___
*[gsc.py, line 226 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxwsF5j2P68EjhDGf:-MkHxwsGErnYI75bk7w3:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L226)):*
> ```Python
>     # generate Dockerfile.compile from Jinja-style templates/Dockerfile.<distro>.compile.template
>     # using the user-provided config file with info on OS distro, Graphene version and SGX driver
>     # and other user-provided args (see argparser::gsc_build_graphene below)
> ```

ditto
___
*[gsc.py, line 230 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxzeM4T7fbMKGOVXW:-MkHxzeM4T7fbMKGOVXX:b-sw21bk) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L230)):*
> ```Python
>     env.globals.update(config)
>     env.globals.update(vars(args))
>     compile_template = env.get_template(f'Dockerfile.{env.globals["Distro"]}.compile.template')
> ```

What about this place?
___
*[gsc.py, line 268 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHy5Qt-iHLGBhgOI8r:-MkHy5Qt-iHLGBhgOI8s:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L268)):*
> ```Python
> 
>     # generate Dockerfile.sign from Jinja-style templates/Dockerfile.<distro>.sign.template
>     # using the user-provided config file with info on OS distro, Graphene version and SGX driver
> ```

ditto
___
*[Documentation/index.rst, line 303 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHyMqX2IDuZpWEZ3fP:-MkHyMqX2IDuZpWEZ3fQ:b-eh8oc0) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/Documentation/index.rst#L303)):*
> ```reStructuredText
> 
>    Defines Linux distribution to be used to build Gramine in. Currently tested
>    distros are Ubuntu 18.04 and Ubuntu 20.04. Default value is ``ubuntu18.04``.
> ```

Shouldn't default value contain `:`?

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: 6 of 8 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxYkoAbBAoO0NAnlI):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, we don't need to prepend `[GSC]` anymore -- we are already in the separate GSC repo, so it is obvious.

I will remove this during final rebase.
</blockquote></details>

Thanks. Have changed it anyways if it helps
___
*[gsc.py, line 164 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxqE076_wOfICYKWQ:-MkLqmM80R7fxRnDMEHO:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is wrong now. Please remove `distro` mentions.
</blockquote></details>

Done.
___
*[gsc.py, line 226 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxwsF5j2P68EjhDGf:-MkLqoEx2GNPEbBTZyMn:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[gsc.py, line 230 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHxzeM4T7fbMKGOVXW:-MkLqqQE9gaBQHrFIr5U:b-8lstt7) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this place?
</blockquote></details>

Done. Sorry about this. Somewhere missed to merge the changes for this flow (build gramine image with sources). Have retested this part now again.
___
*[gsc.py, line 268 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHy5Qt-iHLGBhgOI8r:-MkLqrtO1hCQ0K-_6jG6:bopp4hv) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/gsc.py#L268)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Have done a full scan of the files once again to make i haven't missed anything else. 
___
*[Documentation/index.rst, line 303 at r2](https://reviewable.io/reviews/gramineproject/gsc/14#-MkHyMqX2IDuZpWEZ3fP:-MkLqtrd70G7S_YkALyR:bih5guh) ([raw file](https://github.com/gramineproject/gsc/blob/6be3b91eef9eaec2fea103040334ca47945819fb/Documentation/index.rst#L303)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't default value contain `:`?
</blockquote></details>

yuk! this ones unforgivable!

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-MkbC6EC5s4BUWAYPDWT:b-emrogn) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
> ```Python
>     os.makedirs(tmp_build_path, exist_ok=True)
> 
>     # generate Dockerfile.build from Jinja-style templates/Dockerfile.<distro>.build.template
> ```

I'm not sure if this is a good idea, I doubt you'll be able to create a Dockerfile which is portable between different distros and their versions - e.g. the current one already uses `apt-get` (Debian/Ubuntu-specific) and the package names which are version-specific (some packages change their names in time).

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-MkbDwEX8cI6Jo3jL8Vg:b-g63bew) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if this is a good idea, I doubt you'll be able to create a Dockerfile which is portable between different distros and their versions - e.g. the current one already uses `apt-get` (Debian/Ubuntu-specific) and the package names which are version-specific (some packages change their names in time).
</blockquote></details>

Actually, this change is only to generalize across multiple Ubuntu versions. And  this information is fetched from the config.yaml file during build. Otherwise like you said, its close to impossible to create generic Dockerfile to accomodate multple distros - for ex Ubuntu, CentOS etc.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-MkcRJEr0BuYBhm_QHGj:bnq2uge) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Actually, this change is only to generalize across multiple Ubuntu versions. And  this information is fetched from the config.yaml file during build. Otherwise like you said, its close to impossible to create generic Dockerfile to accomodate multple distros - for ex Ubuntu, CentOS etc. 
</blockquote></details>

The problem I have with the current version is that it pretends to be distro-agnostic (`{{Distro}}` used inside the Dockerfile), but at the same time it's actually bound to Ubuntu 18.04/20.04 (because the package installation commands are Debian/Ubuntu-specific and package names are Ubuntu 18.04/20.04-specific).

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-Mkf4DVqCKw7i9iGcD3j:b1lxm9d) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem I have with the current version is that it pretends to be distro-agnostic (`{{Distro}}` used inside the Dockerfile), but at the same time it's actually bound to Ubuntu 18.04/20.04 (because the package installation commands are Debian/Ubuntu-specific and package names are Ubuntu 18.04/20.04-specific).
</blockquote></details>

@mkow I disagree. Using a tuple of `Dockerfile.<distro>.{compile,build,sign}.template` for each supported OS distro will lead to enormous amount of duplication. Also, it will be a maintanence burden (Gramine finally removed Makefiles -> change *all* the Dockerfiles)... Also, it will be plain ugly. (I think this was the very first version of this PR, with two copies of Ubuntu Dockerfiles, and it looked bad.)

I think it's a much more sensible approach to have one copy of each of these `{compile,build,sign}` Dockerfiles. And to support different quirks of different distros, we can always do Jinja checks (just like we do now for e.g. "insecure args"), e.g. `{% if 'ubuntu' in Distro %}`.

The only places which are distro-specific should be anyway these `apt-get` lines. The rest should be ideally exactly the same for any OS distro and version.

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-MklKKSW4WlINweWiKPt:bt6rbq6) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I disagree. Using a tuple of `Dockerfile.<distro>.{compile,build,sign}.template` for each supported OS distro will lead to enormous amount of duplication. Also, it will be a maintanence burden (Gramine finally removed Makefiles -> change *all* the Dockerfiles)... Also, it will be plain ugly. (I think this was the very first version of this PR, with two copies of Ubuntu Dockerfiles, and it looked bad.)

I think it's a much more sensible approach to have one copy of each of these `{compile,build,sign}` Dockerfiles. And to support different quirks of different distros, we can always do Jinja checks (just like we do now for e.g. "insecure args"), e.g. `{% if 'ubuntu' in Distro %}`.

The only places which are distro-specific should be anyway these `apt-get` lines. The rest should be ideally exactly the same for any OS distro and version.
</blockquote></details>

@mkow  shall we go ahead with this for now?

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib and @dimakuv)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-Mkvf59xBU4gnyEz2t7A:bdo8hb6) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

@mkow  shall we go ahead with this for now? 
</blockquote></details>

@dimakuv We don't need two copies right now, the issue with version is less important. Can we at least have "Ubuntu" in the file name? Right now it's very misleading IMO.

Overall, I think we should just derive from a per-distro Dockerfile in the compile template, that would be cleaner that having `if`s for each possible distro and all versions in this single file.

**Comment by dimakuv** [comment]
___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-MkvjK105E2hTwaqLRkg:bwwnhh7) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
> Overall, I think we should just derive from a per-distro Dockerfile in the compile template, that would be cleaner that having ifs for each possible distro and all versions in this single file.

This suggestion I like.

So you mean that instead of the current chain:
- `Dockerfile.compile.template` -> `Dockerfile.build.template` -> `Dockerfile.sign.template`

We will have this chain:
- `Dockerfile.ubuntu.template` -> `Dockerfile.compile.template` -> `Dockerfile.build.template` -> `Dockerfile.sign.template`

...and all Ubuntu-relevant commands (`apt-get update`, `apt-get install`) will be in this new `Dockerfile.ubuntu.template`, and other three files will have **no distro-specific commands** at all.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-Mkvk6Ct1DprwB1czcqP:buem2p5) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Overall, I think we should just derive from a per-distro Dockerfile in the compile template, that would be cleaner that having ifs for each possible distro and all versions in this single file.

This suggestion I like.

So you mean that instead of the current chain:
- `Dockerfile.compile.template` -> `Dockerfile.build.template` -> `Dockerfile.sign.template`

We will have this chain:
- `Dockerfile.ubuntu.template` -> `Dockerfile.compile.template` -> `Dockerfile.build.template` -> `Dockerfile.sign.template`

...and all Ubuntu-relevant commands (`apt-get update`, `apt-get install`) will be in this new `Dockerfile.ubuntu.template`, and other three files will have **no distro-specific commands** at all.
</blockquote></details>

But that suggestion will require a lot of changes, so I'll just go with the first request from Michal: restore `.ubuntu.` in the file names...

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: 4 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[gsc.py, line 162 at r3](https://reviewable.io/reviews/gramineproject/gsc/14#-MkbC6EC5s4BUWAYPDWS:-MkwCV1i5gvRrxP-Lz6S:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/730bb8ecabf01c847066270ecaca1aaab2b62671/gsc.py#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But that suggestion will require a lot of changes, so I'll just go with the first request from Michal: restore `.ubuntu.` in the file names...
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by aneessahib** [comment]
rebasing got a little messed up. fixing it now

**Comment by aneessahib** [comment]
@mkow rebasing done

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/gramineproject/gsc/14#-Ml-kRc_DZurJHawdpkm):*
> ```
> [GSC] 
> ```

Why adding this? We're in GSC repo ;)

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/gramineproject/gsc/14#-Ml-kRc_DZurJHawdpkm):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> [GSC] 
> ```

Why adding this? We're in GSC repo ;)
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 10 files at r5, 2 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/14)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
